import fs from 'fs';
import path from 'path';

export type HSKEntry = {
  characters: string;
  pinyin: string;
  meaning: string;
  partOfSpeech: string;
  hskLevel: number;
  examples: string[];
  notes?: string;
};

export type TranslatedHSKEntry = HSKEntry & {
  originalMeaning: string;
};

export const HSK_LEVEL_DESCRIPTIONS: Record<number, { title: string; description: string; cefrLevel: string; wordCount: string }> = {
  1: {
    title: 'HSK 1 — Beginner',
    description: 'Basic greetings, numbers, dates, and simple daily phrases. You can introduce yourself and handle simple interactions.',
    cefrLevel: 'A1',
    wordCount: '143 words',
  },
  2: {
    title: 'HSK 2 — Elementary',
    description: 'Shopping, transportation, and basic conversations about daily routines. You can discuss familiar topics in simple terms.',
    cefrLevel: 'A2',
    wordCount: '148 words',
  },
  3: {
    title: 'HSK 3 — Intermediate',
    description: 'Travel, hobbies, and expressing opinions. You can handle most situations while traveling in China.',
    cefrLevel: 'B1',
    wordCount: '600 words',
  },
  4: {
    title: 'HSK 4 — Upper Intermediate',
    description: 'Abstract topics, news, and professional discussions. You can converse fluently with native speakers on a wide range of topics.',
    cefrLevel: 'B2',
    wordCount: '1,200 words',
  },
  5: {
    title: 'HSK 5 — Advanced',
    description: 'Complex texts, formal writing, and nuanced expression. You can read Chinese newspapers and give structured speeches.',
    cefrLevel: 'C1',
    wordCount: '2,500 words',
  },
  6: {
    title: 'HSK 6 — Mastery',
    description: 'Near-native comprehension, academic writing, and subtle cultural expression. You can express yourself effortlessly in any situation.',
    cefrLevel: 'C2',
    wordCount: '5,000+ words',
  },
};

export const hskEntries: HSKEntry[] = [
  // HSK 1 — 143 words
  { characters: '你好', pinyin: 'nǐ hǎo', meaning: 'Hello', partOfSpeech: 'phrase', hskLevel: 1, examples: ['你好，我叫小明。(Hello, my name is Xiao Ming.)'] },
  { characters: '谢谢', pinyin: 'xiè xie', meaning: 'Thank you', partOfSpeech: 'verb', hskLevel: 1, examples: ['谢谢你的帮助。(Thank you for your help.)'] },
  { characters: '再见', pinyin: 'zài jiàn', meaning: 'Goodbye', partOfSpeech: 'phrase', hskLevel: 1, examples: ['明天见，再见！(See you tomorrow, goodbye!)'] },
  { characters: '是', pinyin: 'shì', meaning: 'To be / Yes', partOfSpeech: 'verb', hskLevel: 1, examples: ['我是学生。(I am a student.)'] },
  { characters: '不', pinyin: 'bù', meaning: 'Not / No', partOfSpeech: 'adverb', hskLevel: 1, examples: ['我不喝咖啡。(I don\'t drink coffee.)'] },
  { characters: '我', pinyin: 'wǒ', meaning: 'I / Me', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['我很高兴。(I am very happy.)'] },
  { characters: '他', pinyin: 'tā', meaning: 'He / Him', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['他是我朋友。(He is my friend.)'] },
  { characters: '她', pinyin: 'tā', meaning: 'She / Her', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['她很漂亮。(She is very beautiful.)'] },
  { characters: '好', pinyin: 'hǎo', meaning: 'Good / Well', partOfSpeech: 'adjective', hskLevel: 1, examples: ['今天天气很好。(The weather is great today.)'] },
  { characters: '大', pinyin: 'dà', meaning: 'Big / Large', partOfSpeech: 'adjective', hskLevel: 1, examples: ['这个房间很大。(This room is very big.)'] },
  { characters: '小', pinyin: 'xiǎo', meaning: 'Small / Little', partOfSpeech: 'adjective', hskLevel: 1, examples: ['我有一只小猫。(I have a small cat.)'] },
  { characters: '吃', pinyin: 'chī', meaning: 'To eat', partOfSpeech: 'verb', hskLevel: 1, examples: ['我们去吃饭吧。(Let\'s go eat.)'] },
  { characters: '喝', pinyin: 'hē', meaning: 'To drink', partOfSpeech: 'verb', hskLevel: 1, examples: ['你想喝什么？(What would you like to drink?)'] },
  { characters: '看', pinyin: 'kàn', meaning: 'To look / To watch', partOfSpeech: 'verb', hskLevel: 1, examples: ['我们看电影吧。(Let\'s watch a movie.)'] },
  { characters: '听', pinyin: 'tīng', meaning: 'To listen', partOfSpeech: 'verb', hskLevel: 1, examples: ['我喜欢听音乐。(I like listening to music.)'] },
  { characters: '说', pinyin: 'shuō', meaning: 'To speak / To say', partOfSpeech: 'verb', hskLevel: 1, examples: ['你会说中文吗？(Can you speak Chinese?)'] },
  { characters: '读', pinyin: 'dú', meaning: 'To read', partOfSpeech: 'verb', hskLevel: 1, examples: ['我每天读书。(I read every day.)'] },
  { characters: '写', pinyin: 'xiě', meaning: 'To write', partOfSpeech: 'verb', hskLevel: 1, examples: ['请写你的名字。(Please write your name.)'] },
  { characters: '学', pinyin: 'xué', meaning: 'To study / To learn', partOfSpeech: 'verb', hskLevel: 1, examples: ['我在学中文。(I am studying Chinese.)'] },
  { characters: '朋友', pinyin: 'péng you', meaning: 'Friend', partOfSpeech: 'noun', hskLevel: 1, examples: ['他是我的好朋友。(He is my good friend.)'] },
  { characters: '家', pinyin: 'jiā', meaning: 'Home / Family', partOfSpeech: 'noun', hskLevel: 1, examples: ['欢迎来我家。(Welcome to my home.)'] },
  { characters: '水', pinyin: 'shuǐ', meaning: 'Water', partOfSpeech: 'noun', hskLevel: 1, examples: ['请给我一杯水。(Please give me a glass of water.)'] },
  { characters: '钱', pinyin: 'qián', meaning: 'Money', partOfSpeech: 'noun', hskLevel: 1, examples: ['这个多少钱？(How much is this?)'] },
  { characters: '今天', pinyin: 'jīn tiān', meaning: 'Today', partOfSpeech: 'noun', hskLevel: 1, examples: ['今天星期几？(What day is today?)'] },
  { characters: '明天', pinyin: 'míng tiān', meaning: 'Tomorrow', partOfSpeech: 'noun', hskLevel: 1, examples: ['明天我们去公园。(Tomorrow we go to the park.)'] },
  { characters: '昨天', pinyin: 'zuó tiān', meaning: 'Yesterday', partOfSpeech: 'noun', hskLevel: 1, examples: ['昨天下雨了。(It rained yesterday.)'] },
  { characters: '多少', pinyin: 'duō shǎo', meaning: 'How much / How many', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['你多少岁？(How old are you?)'] },
  { characters: '什么', pinyin: 'shén me', meaning: 'What', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['你叫什么名字？(What is your name?)'] },
  { characters: '哪里', pinyin: 'nǎ lǐ', meaning: 'Where', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['你住在哪里？(Where do you live?)'] },
  { characters: '谁', pinyin: 'shéi', meaning: 'Who', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['这是谁？(Who is this?)'] },

    { characters: '爱', pinyin: 'ài', meaning: 'love', partOfSpeech: 'verb', hskLevel: 1, examples: ['我爱你。(I love you.)'] },
  { characters: '八', pinyin: 'bā', meaning: 'eight', partOfSpeech: 'numeral', hskLevel: 1, examples: ['他有八个苹果。(He has eight apples.)'] },
  { characters: '爸爸', pinyin: 'bàba', meaning: 'father', partOfSpeech: 'noun', hskLevel: 1, examples: ['我爸爸是老师。(My father is a teacher.)'] },
  { characters: '杯子', pinyin: 'bēizi', meaning: 'cup', partOfSpeech: 'noun', hskLevel: 1, examples: ['杯子里有水。(There is water in the cup.)'] },
  { characters: '北京', pinyin: 'Běijīng', meaning: 'Beijing', partOfSpeech: 'noun', hskLevel: 1, examples: ['我住在北京。(I live in Beijing.)'] },
  { characters: '本', pinyin: 'běn', meaning: 'measure word for books', partOfSpeech: 'measure word', hskLevel: 1, examples: ['我有三本书。(I have three books.)'] },
  { characters: '不客气', pinyin: 'bú kèqi', meaning: 'you\'re welcome', partOfSpeech: 'phrase', hskLevel: 1, examples: ['谢谢你！不客气。(Thank you! You\'re welcome.)'] },
  { characters: '菜', pinyin: 'cài', meaning: 'dish', partOfSpeech: 'noun', hskLevel: 1, examples: ['我喜欢中国菜。(I like Chinese food.)'] },
  { characters: '茶', pinyin: 'chá', meaning: 'tea', partOfSpeech: 'noun', hskLevel: 1, examples: ['我喝茶。(I drink tea.)'] },
  { characters: '吃饭', pinyin: 'chī fàn', meaning: 'eat', partOfSpeech: 'verb', hskLevel: 1, examples: ['我们一起吃饭。(Let\'s eat together.)'] },
  { characters: '出', pinyin: 'chū', meaning: 'go out', partOfSpeech: 'verb', hskLevel: 1, examples: ['我出门了。(I went out.)'] },
  { characters: '出租车', pinyin: 'chūzūchē', meaning: 'taxi', partOfSpeech: 'noun', hskLevel: 1, examples: ['我坐出租车去。(I take a taxi.)'] },
  { characters: '打电话', pinyin: 'dǎ diànhuà', meaning: 'make a phone call', partOfSpeech: 'verb', hskLevel: 1, examples: ['我给你打电话。(I call you.)'] },
  { characters: '的', pinyin: 'de', meaning: 'possessive particle', partOfSpeech: 'particle', hskLevel: 1, examples: ['这是我的书。(This is my book.)'] },
  { characters: '点', pinyin: 'diǎn', meaning: 'o\'clock', partOfSpeech: 'measure word', hskLevel: 1, examples: ['现在三点。(It\'s three o\'clock now.)'] },
  { characters: '电脑', pinyin: 'diànnǎo', meaning: 'computer', partOfSpeech: 'noun', hskLevel: 1, examples: ['我用电脑工作。(I use a computer to work.)'] },
  { characters: '电视', pinyin: 'diànshì', meaning: 'television', partOfSpeech: 'noun', hskLevel: 1, examples: ['我在看电视。(I am watching TV.)'] },
  { characters: '电影', pinyin: 'diànyǐng', meaning: 'movie', partOfSpeech: 'noun', hskLevel: 1, examples: ['我喜欢看电影。(I like watching movies.)'] },
  { characters: '东西', pinyin: 'dōngxi', meaning: 'thing', partOfSpeech: 'noun', hskLevel: 1, examples: ['我买了很多东西。(I bought many things.)'] },
  { characters: '都', pinyin: 'dōu', meaning: 'all', partOfSpeech: 'adverb', hskLevel: 1, examples: ['我们都去。(We all go.)'] },
  { characters: '对不起', pinyin: 'duìbuqǐ', meaning: 'sorry', partOfSpeech: 'phrase', hskLevel: 1, examples: ['对不起，我迟到了。(Sorry, I am late.)'] },
  { characters: '多', pinyin: 'duō', meaning: 'many', partOfSpeech: 'adjective', hskLevel: 1, examples: ['这里的人很多。(There are many people here.)'] },
  { characters: '儿子', pinyin: 'érzi', meaning: 'son', partOfSpeech: 'noun', hskLevel: 1, examples: ['我有一个儿子。(I have a son.)'] },
  { characters: '二', pinyin: 'èr', meaning: 'two', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有两个苹果。(I have two apples.)'] },
  { characters: '饭店', pinyin: 'fàndiàn', meaning: 'restaurant', partOfSpeech: 'noun', hskLevel: 1, examples: ['我们去饭店吃饭。(We go to the restaurant to eat.)'] },
  { characters: '飞机', pinyin: 'fēijī', meaning: 'airplane', partOfSpeech: 'noun', hskLevel: 1, examples: ['我坐飞机去北京。(I take a plane to Beijing.)'] },
  { characters: '分钟', pinyin: 'fēnzhōng', meaning: 'minute', partOfSpeech: 'measure word', hskLevel: 1, examples: ['我等了十分钟。(I waited for ten minutes.)'] },
  { characters: '高兴', pinyin: 'gāoxìng', meaning: 'happy', partOfSpeech: 'adjective', hskLevel: 1, examples: ['我很高兴。(I am very happy.)'] },
  { characters: '个', pinyin: 'gè', meaning: 'measure word', partOfSpeech: 'measure word', hskLevel: 1, examples: ['一个人。(One person.)'] },
  { characters: '工作', pinyin: 'gōngzuò', meaning: 'work', partOfSpeech: 'noun', hskLevel: 1, examples: ['我在工作。(I am working.)'] },
  { characters: '狗', pinyin: 'gǒu', meaning: 'dog', partOfSpeech: 'noun', hskLevel: 1, examples: ['我有一只狗。(I have a dog.)'] },
  { characters: '汉语', pinyin: 'Hànyǔ', meaning: 'Chinese language', partOfSpeech: 'noun', hskLevel: 1, examples: ['我在学汉语。(I am learning Chinese.)'] },
  { characters: '号', pinyin: 'hào', meaning: 'date', partOfSpeech: 'noun', hskLevel: 1, examples: ['今天是几号？(What is the date today?)'] },
  { characters: '和', pinyin: 'hé', meaning: 'and', partOfSpeech: 'conjunction', hskLevel: 1, examples: ['我和你。(You and I.)'] },
  { characters: '很', pinyin: 'hěn', meaning: 'very', partOfSpeech: 'adverb', hskLevel: 1, examples: ['我很高兴。(I am very happy.)'] },
  { characters: '后面', pinyin: 'hòumiàn', meaning: 'behind', partOfSpeech: 'noun', hskLevel: 1, examples: ['房子后面有个花园。(There is a garden behind the house.)'] },
  { characters: '回', pinyin: 'huí', meaning: 'return', partOfSpeech: 'verb', hskLevel: 1, examples: ['我回家。(I return home.)'] },
  { characters: '会', pinyin: 'huì', meaning: 'can', partOfSpeech: 'verb', hskLevel: 1, examples: ['我会说汉语。(I can speak Chinese.)'] },
  { characters: '几', pinyin: 'jǐ', meaning: 'how many', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['你有几个苹果？(How many apples do you have?)'] },
  { characters: '叫', pinyin: 'jiào', meaning: 'call', partOfSpeech: 'verb', hskLevel: 1, examples: ['我叫李明。(My name is Li Ming.)'] },
  { characters: '九', pinyin: 'jiǔ', meaning: 'nine', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有九个朋友。(I have nine friends.)'] },
  { characters: '开', pinyin: 'kāi', meaning: 'open', partOfSpeech: 'verb', hskLevel: 1, examples: ['请开门。(Please open the door.)'] },
  { characters: '看见', pinyin: 'kànjiàn', meaning: 'see', partOfSpeech: 'verb', hskLevel: 1, examples: ['我看见他了。(I saw him.)'] },
  { characters: '块', pinyin: 'kuài', meaning: 'measure word for money', partOfSpeech: 'measure word', hskLevel: 1, examples: ['这个五块钱。(This is five yuan.)'] },
  { characters: '来', pinyin: 'lái', meaning: 'come', partOfSpeech: 'verb', hskLevel: 1, examples: ['请你来。(Please come.)'] },
  { characters: '老师', pinyin: 'lǎoshī', meaning: 'teacher', partOfSpeech: 'noun', hskLevel: 1, examples: ['他是我的老师。(He is my teacher.)'] },
  { characters: '了', pinyin: 'le', meaning: 'particle indicating change', partOfSpeech: 'particle', hskLevel: 1, examples: ['我吃饭了。(I have eaten.)'] },
  { characters: '冷', pinyin: 'lěng', meaning: 'cold', partOfSpeech: 'adjective', hskLevel: 1, examples: ['今天很冷。(It is very cold today.)'] },
  { characters: '里', pinyin: 'lǐ', meaning: 'inside', partOfSpeech: 'noun', hskLevel: 1, examples: ['房子里有很多人。(There are many people inside the house.)'] },
  { characters: '六', pinyin: 'liù', meaning: 'six', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有六本书。(I have six books.)'] },
  { characters: '妈妈', pinyin: 'māma', meaning: 'mother', partOfSpeech: 'noun', hskLevel: 1, examples: ['我妈妈是医生。(My mother is a doctor.)'] },
  { characters: '吗', pinyin: 'ma', meaning: 'question particle', partOfSpeech: 'particle', hskLevel: 1, examples: ['你好吗？(How are you?)'] },
  { characters: '猫', pinyin: 'māo', meaning: 'cat', partOfSpeech: 'noun', hskLevel: 1, examples: ['我家有一只猫。(I have a cat at home.)'] },
  { characters: '没关系', pinyin: 'méi guānxi', meaning: 'it\'s okay', partOfSpeech: 'phrase', hskLevel: 1, examples: ['对不起！没关系。(Sorry! It\'s okay.)'] },
  { characters: '米饭', pinyin: 'mǐfàn', meaning: 'rice', partOfSpeech: 'noun', hskLevel: 1, examples: ['我喜欢吃米饭。(I like to eat rice.)'] },
  { characters: '名字', pinyin: 'míngzi', meaning: 'name', partOfSpeech: 'noun', hskLevel: 1, examples: ['你的名字是什么？(What is your name?)'] },
  { characters: '哪', pinyin: 'nǎ', meaning: 'which', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['你是哪国人？(Which country are you from?)'] },
  { characters: '那', pinyin: 'nà', meaning: 'that', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['那是我的书。(That is my book.)'] },
  { characters: '呢', pinyin: 'ne', meaning: 'question particle', partOfSpeech: 'particle', hskLevel: 1, examples: ['你呢？(How about you?)'] },
  { characters: '能', pinyin: 'néng', meaning: 'can', partOfSpeech: 'verb', hskLevel: 1, examples: ['我能说汉语。(I can speak Chinese.)'] },
  { characters: '前面', pinyin: 'qiánmiàn', meaning: 'front', partOfSpeech: 'noun', hskLevel: 1, examples: ['前面有一个商店。(There is a shop in front.)'] },
  { characters: '请', pinyin: 'qǐng', meaning: 'please', partOfSpeech: 'verb', hskLevel: 1, examples: ['请坐。(Please sit.)'] },
  { characters: '去', pinyin: 'qù', meaning: 'go', partOfSpeech: 'verb', hskLevel: 1, examples: ['我去学校。(I go to school.)'] },
  { characters: '热', pinyin: 'rè', meaning: 'hot', partOfSpeech: 'adjective', hskLevel: 1, examples: ['今天很热。(Today is hot.)'] },
  { characters: '人', pinyin: 'rén', meaning: 'person', partOfSpeech: 'noun', hskLevel: 1, examples: ['他是一个好人。(He is a good person.)'] },
  { characters: '认识', pinyin: 'rènshi', meaning: 'know', partOfSpeech: 'verb', hskLevel: 1, examples: ['我认识他。(I know him.)'] },
  { characters: '三', pinyin: 'sān', meaning: 'three', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有三本书。(I have three books.)'] },
  { characters: '商店', pinyin: 'shāngdiàn', meaning: 'shop', partOfSpeech: 'noun', hskLevel: 1, examples: ['我去商店买东西。(I go to the shop to buy things.)'] },
  { characters: '上', pinyin: 'shàng', meaning: 'up', partOfSpeech: 'preposition', hskLevel: 1, examples: ['书在桌子上。(The book is on the table.)'] },
  { characters: '上午', pinyin: 'shàngwǔ', meaning: 'morning', partOfSpeech: 'noun', hskLevel: 1, examples: ['我上午去学校。(I go to school in the morning.)'] },
  { characters: '少', pinyin: 'shǎo', meaning: 'few', partOfSpeech: 'adjective', hskLevel: 1, examples: ['这里人很少。(There are few people here.)'] },
  { characters: '十', pinyin: 'shí', meaning: 'ten', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有十个苹果。(I have ten apples.)'] },
  { characters: '时候', pinyin: 'shíhou', meaning: 'time', partOfSpeech: 'noun', hskLevel: 1, examples: ['你什么时候回来？(When will you come back?)'] },
  { characters: '书', pinyin: 'shū', meaning: 'book', partOfSpeech: 'noun', hskLevel: 1, examples: ['我喜欢看书。(I like reading books.)'] },
  { characters: '水果', pinyin: 'shuǐguǒ', meaning: 'fruit', partOfSpeech: 'noun', hskLevel: 1, examples: ['我喜欢吃水果。(I like eating fruit.)'] },
  { characters: '睡觉', pinyin: 'shuìjiào', meaning: 'sleep', partOfSpeech: 'verb', hskLevel: 1, examples: ['我晚上十点睡觉。(I sleep at ten in the evening.)'] },
  { characters: '四', pinyin: 'sì', meaning: 'four', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有四个朋友。(I have four friends.)'] },
  { characters: '岁', pinyin: 'suì', meaning: 'years old', partOfSpeech: 'measure word', hskLevel: 1, examples: ['我今年二十岁。(I am twenty years old this year.)'] },
  { characters: '太', pinyin: 'tài', meaning: 'too', partOfSpeech: 'adverb', hskLevel: 1, examples: ['太好了！(Great!)'] },
  { characters: '天气', pinyin: 'tiānqì', meaning: 'weather', partOfSpeech: 'noun', hskLevel: 1, examples: ['今天天气很好。(The weather is good today.)'] },
  { characters: '同学', pinyin: 'tóngxué', meaning: 'classmate', partOfSpeech: 'noun', hskLevel: 1, examples: ['他是我的同学。(He is my classmate.)'] },
  { characters: '喂', pinyin: 'wèi', meaning: 'hello (on the phone)', partOfSpeech: 'phrase', hskLevel: 1, examples: ['喂，你好！(Hello, how are you?)'] },
  { characters: '我们', pinyin: 'wǒmen', meaning: 'we', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['我们都是好朋友。(We are all good friends.)'] },
  { characters: '五', pinyin: 'wǔ', meaning: 'five', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有五个苹果。(I have five apples.)'] },
  { characters: '喜欢', pinyin: 'xǐhuan', meaning: 'like', partOfSpeech: 'verb', hskLevel: 1, examples: ['我喜欢吃苹果。(I like eating apples.)'] },
  { characters: '下', pinyin: 'xià', meaning: 'down', partOfSpeech: 'preposition', hskLevel: 1, examples: ['书在桌子下。(The book is under the table.)'] },
  { characters: '下午', pinyin: 'xiàwǔ', meaning: 'afternoon', partOfSpeech: 'noun', hskLevel: 1, examples: ['我下午去商店。(I go to the shop in the afternoon.)'] },
  { characters: '下雨', pinyin: 'xiàyǔ', meaning: 'rain', partOfSpeech: 'verb', hskLevel: 1, examples: ['今天下雨了。(It rained today.)'] },
  { characters: '先生', pinyin: 'xiānsheng', meaning: 'Mr.', partOfSpeech: 'noun', hskLevel: 1, examples: ['王先生是我的老师。(Mr. Wang is my teacher.)'] },
  { characters: '现在', pinyin: 'xiànzài', meaning: 'now', partOfSpeech: 'adverb', hskLevel: 1, examples: ['我现在在学校。(I am at school now.)'] },
  { characters: '想', pinyin: 'xiǎng', meaning: 'want', partOfSpeech: 'verb', hskLevel: 1, examples: ['我想吃饭。(I want to eat.)'] },
  { characters: '小姐', pinyin: 'xiǎojiě', meaning: 'Miss', partOfSpeech: 'noun', hskLevel: 1, examples: ['李小姐是我的朋友。(Miss Li is my friend.)'] },
  { characters: '些', pinyin: 'xiē', meaning: 'some', partOfSpeech: 'measure word', hskLevel: 1, examples: ['我买了一些水果。(I bought some fruits.)'] },
  { characters: '星期', pinyin: 'xīngqī', meaning: 'week', partOfSpeech: 'noun', hskLevel: 1, examples: ['今天是星期一。(Today is Monday.)'] },
  { characters: '学生', pinyin: 'xuésheng', meaning: 'student', partOfSpeech: 'noun', hskLevel: 1, examples: ['他是一个好学生。(He is a good student.)'] },
  { characters: '学习', pinyin: 'xuéxí', meaning: 'study', partOfSpeech: 'verb', hskLevel: 1, examples: ['我在学习汉语。(I am studying Chinese.)'] },
  { characters: '学校', pinyin: 'xuéxiào', meaning: 'school', partOfSpeech: 'noun', hskLevel: 1, examples: ['我在学校上课。(I attend classes at school.)'] },
  { characters: '一', pinyin: 'yī', meaning: 'one', partOfSpeech: 'numeral', hskLevel: 1, examples: ['我有一个苹果。(I have one apple.)'] },
  { characters: '衣服', pinyin: 'yīfu', meaning: 'clothes', partOfSpeech: 'noun', hskLevel: 1, examples: ['我买了新衣服。(I bought new clothes.)'] },
  { characters: '医生', pinyin: 'yīshēng', meaning: 'doctor', partOfSpeech: 'noun', hskLevel: 1, examples: ['他是医生。(He is a doctor.)'] },
  { characters: '医院', pinyin: 'yīyuàn', meaning: 'hospital', partOfSpeech: 'noun', hskLevel: 1, examples: ['我去医院看病。(I go to the hospital to see a doctor.)'] },
  { characters: '椅子', pinyin: 'yǐzi', meaning: 'chair', partOfSpeech: 'noun', hskLevel: 1, examples: ['请坐在椅子上。(Please sit on the chair.)'] },
  { characters: '有', pinyin: 'yǒu', meaning: 'have', partOfSpeech: 'verb', hskLevel: 1, examples: ['我有一本书。(I have a book.)'] },
  { characters: '月', pinyin: 'yuè', meaning: 'month', partOfSpeech: 'noun', hskLevel: 1, examples: ['这个月我很忙。(I am busy this month.)'] },
  { characters: '在', pinyin: 'zài', meaning: 'at', partOfSpeech: 'preposition', hskLevel: 1, examples: ['我在家。(I am at home.)'] },
  { characters: '怎么', pinyin: 'zěnme', meaning: 'how', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['你怎么去学校？(How do you go to school?)'] },
  { characters: '怎么样', pinyin: 'zěnmeyàng', meaning: 'how about', partOfSpeech: 'phrase', hskLevel: 1, examples: ['今天天气怎么样？(How is the weather today?)'] },
  { characters: '这', pinyin: 'zhè', meaning: 'this', partOfSpeech: 'pronoun', hskLevel: 1, examples: ['这是我的书。(This is my book.)'] },
  { characters: '中国', pinyin: 'Zhōngguó', meaning: 'China', partOfSpeech: 'noun', hskLevel: 1, examples: ['我去过中国。(I have been to China.)'] },
  { characters: '中午', pinyin: 'zhōngwǔ', meaning: 'noon', partOfSpeech: 'noun', hskLevel: 1, examples: ['我们中午吃饭。(We eat at noon.)'] },
  { characters: '住', pinyin: 'zhù', meaning: 'live', partOfSpeech: 'verb', hskLevel: 1, examples: ['我住在北京。(I live in Beijing.)'] },
  { characters: '桌子', pinyin: 'zhuōzi', meaning: 'table', partOfSpeech: 'noun', hskLevel: 1, examples: ['书在桌子上。(The book is on the table.)'] },
  { characters: '字', pinyin: 'zì', meaning: 'character', partOfSpeech: 'noun', hskLevel: 1, examples: ['这个字怎么写？(How do you write this character?)'] },

  // HSK 2 — 148 words
  { characters: '因为', pinyin: 'yīn wèi', meaning: 'Because', partOfSpeech: 'conjunction', hskLevel: 2, examples: ['因为下雨，所以我没去。(Because it rained, I didn\'t go.)'] },
  { characters: '所以', pinyin: 'suǒ yǐ', meaning: 'So / Therefore', partOfSpeech: 'conjunction', hskLevel: 2, examples: ['他病了，所以没来。(He\'s sick, so he didn\'t come.)'] },
  { characters: '但是', pinyin: 'dàn shì', meaning: 'But / However', partOfSpeech: 'conjunction', hskLevel: 2, examples: ['贵，但是很好吃。(Expensive, but very delicious.)'] },
  { characters: '已经', pinyin: 'yǐ jīng', meaning: 'Already', partOfSpeech: 'adverb', hskLevel: 2, examples: ['我已经吃过了。(I have already eaten.)'] },
  { characters: '可以', pinyin: 'kě yǐ', meaning: 'Can / May', partOfSpeech: 'verb', hskLevel: 2, examples: ['我可以进来吗？(May I come in?)'] },
  { characters: '快', pinyin: 'kuài', meaning: 'Fast / Quick', partOfSpeech: 'adjective', hskLevel: 2, examples: ['你走得太快了。(You walk too fast.)'] },
  { characters: '慢', pinyin: 'màn', meaning: 'Slow', partOfSpeech: 'adjective', hskLevel: 2, examples: ['请说慢一点。(Please speak slower.)'] },
  { characters: '忙', pinyin: 'máng', meaning: 'Busy', partOfSpeech: 'adjective', hskLevel: 2, examples: ['最近我很忙。(I\'ve been busy recently.)'] },
  { characters: '远', pinyin: 'yuǎn', meaning: 'Far', partOfSpeech: 'adjective', hskLevel: 2, examples: ['学校离这里很远。(The school is far from here.)'] },
  { characters: '近', pinyin: 'jìn', meaning: 'Near / Close', partOfSpeech: 'adjective', hskLevel: 2, examples: ['超市离我家很近。(The supermarket is close to my home.)'] },
  { characters: '帮助', pinyin: 'bāng zhù', meaning: 'To help', partOfSpeech: 'verb', hskLevel: 2, examples: ['谢谢你帮助我。(Thank you for helping me.)'] },
  { characters: '准备', pinyin: 'zhǔn bèi', meaning: 'To prepare', partOfSpeech: 'verb', hskLevel: 2, examples: ['你准备好了吗？(Are you ready?)'] },
  { characters: '开始', pinyin: 'kāi shǐ', meaning: 'To begin / To start', partOfSpeech: 'verb', hskLevel: 2, examples: ['比赛开始了。(The game has started.)'] },
  { characters: '知道', pinyin: 'zhī dào', meaning: 'To know', partOfSpeech: 'verb', hskLevel: 2, examples: ['我不知道。(I don\'t know.)'] },
  { characters: '觉得', pinyin: 'jué de', meaning: 'To think / To feel', partOfSpeech: 'verb', hskLevel: 2, examples: ['你觉得怎么样？(What do you think?)'] },
  { characters: '希望', pinyin: 'xī wàng', meaning: 'To hope / Hope', partOfSpeech: 'verb', hskLevel: 2, examples: ['我希望明天天气好。(I hope the weather is good tomorrow.)'] },
  { characters: '旁边', pinyin: 'páng biān', meaning: 'Beside / Next to', partOfSpeech: 'noun', hskLevel: 2, examples: ['银行在超市旁边。(The bank is next to the supermarket.)'] },
  { characters: '机场', pinyin: 'jī chǎng', meaning: 'Airport', partOfSpeech: 'noun', hskLevel: 2, examples: ['去机场要多久？(How long does it take to get to the airport?)'] },
  { characters: '地铁', pinyin: 'dì tiě', meaning: 'Subway / Metro', partOfSpeech: 'noun', hskLevel: 2, examples: ['我坐地铁去上班。(I take the subway to work.)'] },
  { characters: '手机', pinyin: 'shǒu jī', meaning: 'Mobile phone', partOfSpeech: 'noun', hskLevel: 2, examples: ['我的手机没电了。(My phone is out of battery.)'] },
  { characters: '生日', pinyin: 'shēng rì', meaning: 'Birthday', partOfSpeech: 'noun', hskLevel: 2, examples: ['生日快乐！(Happy birthday!)'] },
  { characters: '身体', pinyin: 'shēn tǐ', meaning: 'Body / Health', partOfSpeech: 'noun', hskLevel: 2, examples: ['注意身体。(Take care of your health.)'] },
  { characters: '眼睛', pinyin: 'yǎn jīng', meaning: 'Eye(s)', partOfSpeech: 'noun', hskLevel: 2, examples: ['她的眼睛很漂亮。(Her eyes are very beautiful.)'] },
  { characters: '虽然', pinyin: 'suī rán', meaning: 'Although', partOfSpeech: 'conjunction', hskLevel: 2, examples: ['虽然很累，但我很开心。(Although tired, I\'m very happy.)'] },
  { characters: '还是', pinyin: 'hái shì', meaning: 'Or / Still', partOfSpeech: 'conjunction', hskLevel: 2, examples: ['你喝茶还是咖啡？(Do you drink tea or coffee?)'] },
  { characters: '一起', pinyin: 'yī qǐ', meaning: 'Together', partOfSpeech: 'adverb', hskLevel: 2, examples: ['我们一起去吧。(Let\'s go together.)'] },
  { characters: '经常', pinyin: 'jīng cháng', meaning: 'Often / Frequently', partOfSpeech: 'adverb', hskLevel: 2, examples: ['我经常运动。(I exercise often.)'] },
  { characters: '非常', pinyin: 'fēi cháng', meaning: 'Very / Extremely', partOfSpeech: 'adverb', hskLevel: 2, examples: ['非常感谢！(Thank you very much!)'] },
  { characters: '可能', pinyin: 'kě néng', meaning: 'Maybe / Possible', partOfSpeech: 'adverb', hskLevel: 2, examples: ['明天可能下雨。(It might rain tomorrow.)'] },
  { characters: '一定', pinyin: 'yī dìng', meaning: 'Definitely / Must', partOfSpeech: 'adverb', hskLevel: 2, examples: ['你一定会成功。(You will definitely succeed.)'] },

    { characters: '白', pinyin: 'bái', meaning: 'white', partOfSpeech: 'adjective', hskLevel: 2, examples: ['这是一只白猫。(This is a white cat.)'] },
  { characters: '百', pinyin: 'bǎi', meaning: 'hundred', partOfSpeech: 'numeral', hskLevel: 2, examples: ['这里有一百个人。(There are one hundred people here.)'] },
  { characters: '报纸', pinyin: 'bàozhǐ', meaning: 'newspaper', partOfSpeech: 'noun', hskLevel: 2, examples: ['我每天看报纸。(I read the newspaper every day.)'] },
  { characters: '比', pinyin: 'bǐ', meaning: 'compare', partOfSpeech: 'preposition', hskLevel: 2, examples: ['他比我高。(He is taller than me.)'] },
  { characters: '别', pinyin: 'bié', meaning: 'don\'t', partOfSpeech: 'adverb', hskLevel: 2, examples: ['别说话。(Don\'t talk.)'] },
  { characters: '宾馆', pinyin: 'bīnguǎn', meaning: 'hotel', partOfSpeech: 'noun', hskLevel: 2, examples: ['我们住在宾馆。(We are staying at a hotel.)'] },
  { characters: '长', pinyin: 'cháng', meaning: 'long', partOfSpeech: 'adjective', hskLevel: 2, examples: ['这条路很长。(This road is very long.)'] },
  { characters: '唱歌', pinyin: 'chànggē', meaning: 'sing', partOfSpeech: 'verb', hskLevel: 2, examples: ['她喜欢唱歌。(She likes to sing.)'] },
  { characters: '穿', pinyin: 'chuān', meaning: 'wear', partOfSpeech: 'verb', hskLevel: 2, examples: ['她穿了一件红色的衣服。(She is wearing a red dress.)'] },
  { characters: '次', pinyin: 'cì', meaning: 'time', partOfSpeech: 'measure word', hskLevel: 2, examples: ['我去过两次北京。(I have been to Beijing twice.)'] },
  { characters: '从', pinyin: 'cóng', meaning: 'from', partOfSpeech: 'preposition', hskLevel: 2, examples: ['我从中国来。(I come from China.)'] },
  { characters: '错', pinyin: 'cuò', meaning: 'wrong', partOfSpeech: 'adjective', hskLevel: 2, examples: ['这道题你做错了。(You got this question wrong.)'] },
  { characters: '打篮球', pinyin: 'dǎ lánqiú', meaning: 'play basketball', partOfSpeech: 'verb', hskLevel: 2, examples: ['我喜欢打篮球。(I like to play basketball.)'] },
  { characters: '大家', pinyin: 'dàjiā', meaning: 'everyone', partOfSpeech: 'pronoun', hskLevel: 2, examples: ['大家好！(Hello everyone!)'] },
  { characters: '到', pinyin: 'dào', meaning: 'arrive', partOfSpeech: 'verb', hskLevel: 2, examples: ['我到家了。(I have arrived home.)'] },
  { characters: '得', pinyin: 'de', meaning: 'particle', partOfSpeech: 'particle', hskLevel: 2, examples: ['他跑得很快。(He runs very fast.)'] },
  { characters: '等', pinyin: 'děng', meaning: 'wait', partOfSpeech: 'verb', hskLevel: 2, examples: ['请等一下。(Please wait a moment.)'] },
  { characters: '弟弟', pinyin: 'dìdi', meaning: 'younger brother', partOfSpeech: 'noun', hskLevel: 2, examples: ['我有一个弟弟。(I have a younger brother.)'] },
  { characters: '第一', pinyin: 'dì yī', meaning: 'first', partOfSpeech: 'numeral', hskLevel: 2, examples: ['他是第一名。(He is the first.)'] },
  { characters: '懂', pinyin: 'dǒng', meaning: 'understand', partOfSpeech: 'verb', hskLevel: 2, examples: ['我懂你的意思。(I understand what you mean.)'] },
  { characters: '对', pinyin: 'duì', meaning: 'correct', partOfSpeech: 'adjective', hskLevel: 2, examples: ['你的答案是对的。(Your answer is correct.)'] },
  { characters: '房间', pinyin: 'fángjiān', meaning: 'room', partOfSpeech: 'noun', hskLevel: 2, examples: ['这是我的房间。(This is my room.)'] },
  { characters: '服务员', pinyin: 'fúwùyuán', meaning: 'waiter', partOfSpeech: 'noun', hskLevel: 2, examples: ['服务员，请给我菜单。(Waiter, please give me the menu.)'] },
  { characters: '高', pinyin: 'gāo', meaning: 'tall', partOfSpeech: 'adjective', hskLevel: 2, examples: ['他很高。(He is tall.)'] },
  { characters: '告诉', pinyin: 'gàosu', meaning: 'tell', partOfSpeech: 'verb', hskLevel: 2, examples: ['请告诉我你的名字。(Please tell me your name.)'] },
  { characters: '哥哥', pinyin: 'gēge', meaning: 'older brother', partOfSpeech: 'noun', hskLevel: 2, examples: ['我有一个哥哥。(I have an older brother.)'] },
  { characters: '给', pinyin: 'gěi', meaning: 'give', partOfSpeech: 'verb', hskLevel: 2, examples: ['请给我一杯水。(Please give me a glass of water.)'] },
  { characters: '公共汽车', pinyin: 'gōnggòng qìchē', meaning: 'bus', partOfSpeech: 'noun', hskLevel: 2, examples: ['我坐公共汽车去上班。(I take the bus to work.)'] },
  { characters: '公司', pinyin: 'gōngsī', meaning: 'company', partOfSpeech: 'noun', hskLevel: 2, examples: ['我在一家大公司工作。(I work at a big company.)'] },
  { characters: '贵', pinyin: 'guì', meaning: 'expensive', partOfSpeech: 'adjective', hskLevel: 2, examples: ['这件衣服很贵。(This piece of clothing is expensive.)'] },
  { characters: '过', pinyin: 'guò', meaning: 'pass', partOfSpeech: 'verb', hskLevel: 2, examples: ['我过了考试。(I passed the exam.)'] },
  { characters: '还', pinyin: 'hái', meaning: 'still', partOfSpeech: 'adverb', hskLevel: 2, examples: ['他还在睡觉。(He is still sleeping.)'] },
  { characters: '孩子', pinyin: 'háizi', meaning: 'child', partOfSpeech: 'noun', hskLevel: 2, examples: ['那个孩子很可爱。(That child is very cute.)'] },
  { characters: '好吃', pinyin: 'hǎochī', meaning: 'delicious', partOfSpeech: 'adjective', hskLevel: 2, examples: ['这道菜很好吃。(This dish is delicious.)'] },
  { characters: '黑', pinyin: 'hēi', meaning: 'black', partOfSpeech: 'adjective', hskLevel: 2, examples: ['他穿了一件黑色的衣服。(He is wearing black clothes.)'] },
  { characters: '红', pinyin: 'hóng', meaning: 'red', partOfSpeech: 'adjective', hskLevel: 2, examples: ['她喜欢红色。(She likes red.)'] },
  { characters: '欢迎', pinyin: 'huānyíng', meaning: 'welcome', partOfSpeech: 'verb', hskLevel: 2, examples: ['欢迎来到中国。(Welcome to China.)'] },
  { characters: '回答', pinyin: 'huídá', meaning: 'answer', partOfSpeech: 'verb', hskLevel: 2, examples: ['请回答我的问题。(Please answer my question.)'] },
  { characters: '鸡蛋', pinyin: 'jīdàn', meaning: 'egg', partOfSpeech: 'noun', hskLevel: 2, examples: ['我早餐吃鸡蛋。(I eat eggs for breakfast.)'] },
  { characters: '件', pinyin: 'jiàn', meaning: 'measure word for clothes', partOfSpeech: 'measure word', hskLevel: 2, examples: ['这是一件新衣服。(This is a new piece of clothing.)'] },
  { characters: '教室', pinyin: 'jiàoshì', meaning: 'classroom', partOfSpeech: 'noun', hskLevel: 2, examples: ['我们在教室上课。(We have class in the classroom.)'] },
  { characters: '姐姐', pinyin: 'jiějie', meaning: 'older sister', partOfSpeech: 'noun', hskLevel: 2, examples: ['我有一个姐姐。(I have an older sister.)'] },
  { characters: '介绍', pinyin: 'jièshào', meaning: 'introduce', partOfSpeech: 'verb', hskLevel: 2, examples: ['请介绍一下你自己。(Please introduce yourself.)'] },
  { characters: '进', pinyin: 'jìn', meaning: 'enter', partOfSpeech: 'verb', hskLevel: 2, examples: ['请进。(Please come in.)'] },
  { characters: '就', pinyin: 'jiù', meaning: 'then', partOfSpeech: 'adverb', hskLevel: 2, examples: ['我一到家就给你打电话。(I will call you as soon as I get home.)'] },
  { characters: '咖啡', pinyin: 'kāfēi', meaning: 'coffee', partOfSpeech: 'noun', hskLevel: 2, examples: ['我每天早上喝咖啡。(I drink coffee every morning.)'] },
  { characters: '考试', pinyin: 'kǎoshì', meaning: 'exam', partOfSpeech: 'noun', hskLevel: 2, examples: ['我明天有一个考试。(I have an exam tomorrow.)'] },
  { characters: '快乐', pinyin: 'kuàilè', meaning: 'happy', partOfSpeech: 'adjective', hskLevel: 2, examples: ['祝你生日快乐！(Wish you a happy birthday!)'] },
  { characters: '累', pinyin: 'lèi', meaning: 'tired', partOfSpeech: 'adjective', hskLevel: 2, examples: ['我今天很累。(I am very tired today.)'] },
  { characters: '两', pinyin: 'liǎng', meaning: 'two', partOfSpeech: 'numeral', hskLevel: 2, examples: ['我有两只猫。(I have two cats.)'] },
  { characters: '路', pinyin: 'lù', meaning: 'road', partOfSpeech: 'noun', hskLevel: 2, examples: ['这条路很长。(This road is very long.)'] },
  { characters: '旅游', pinyin: 'lǚyóu', meaning: 'travel', partOfSpeech: 'verb', hskLevel: 2, examples: ['我喜欢旅游。(I like to travel.)'] },
  { characters: '卖', pinyin: 'mài', meaning: 'sell', partOfSpeech: 'verb', hskLevel: 2, examples: ['他在市场卖水果。(He sells fruit at the market.)'] },
  { characters: '每', pinyin: 'měi', meaning: 'every', partOfSpeech: 'pronoun', hskLevel: 2, examples: ['我每天都跑步。(I run every day.)'] },
  { characters: '妹妹', pinyin: 'mèimei', meaning: 'younger sister', partOfSpeech: 'noun', hskLevel: 2, examples: ['我有一个妹妹。(I have a younger sister.)'] },
  { characters: '门', pinyin: 'mén', meaning: 'door', partOfSpeech: 'noun', hskLevel: 2, examples: ['请关门。(Please close the door.)'] },
  { characters: '男人', pinyin: 'nánrén', meaning: 'man', partOfSpeech: 'noun', hskLevel: 2, examples: ['那个男人是谁？(Who is that man?)'] },
  { characters: '您', pinyin: 'nín', meaning: 'you (polite)', partOfSpeech: 'pronoun', hskLevel: 2, examples: ['您好！(Hello to you!)'] },
  { characters: '牛奶', pinyin: 'niú nǎi', meaning: 'milk', partOfSpeech: 'noun', hskLevel: 2, examples: ['我每天早上喝牛奶。(I drink milk every morning.)'] },
  { characters: '女儿', pinyin: 'nǚ ér', meaning: 'daughter', partOfSpeech: 'noun', hskLevel: 2, examples: ['她的女儿很可爱。(Her daughter is very cute.)'] },
  { characters: '跑步', pinyin: 'pǎo bù', meaning: 'to run', partOfSpeech: 'verb', hskLevel: 2, examples: ['我每天早上去公园跑步。(I go running in the park every morning.)'] },
  { characters: '便宜', pinyin: 'piányi', meaning: 'cheap', partOfSpeech: 'adjective', hskLevel: 2, examples: ['这件衣服很便宜。(This piece of clothing is very cheap.)'] },
  { characters: '票', pinyin: 'piào', meaning: 'ticket', partOfSpeech: 'noun', hskLevel: 2, examples: ['我买了两张电影票。(I bought two movie tickets.)'] },
  { characters: '妻子', pinyin: 'qīzi', meaning: 'wife', partOfSpeech: 'noun', hskLevel: 2, examples: ['他和他的妻子一起去旅行。(He went traveling with his wife.)'] },
  { characters: '起床', pinyin: 'qǐ chuáng', meaning: 'to get up', partOfSpeech: 'verb', hskLevel: 2, examples: ['我每天六点起床。(I get up at six every day.)'] },
  { characters: '千', pinyin: 'qiān', meaning: 'thousand', partOfSpeech: 'numeral', hskLevel: 2, examples: ['这个城市有一千万人。(This city has ten million people.)'] },
  { characters: '晴', pinyin: 'qíng', meaning: 'sunny', partOfSpeech: 'adjective', hskLevel: 2, examples: ['今天是晴天。(Today is a sunny day.)'] },
  { characters: '去年', pinyin: 'qùnián', meaning: 'last year', partOfSpeech: 'noun', hskLevel: 2, examples: ['我去年去了中国。(I went to China last year.)'] },
  { characters: '让', pinyin: 'ràng', meaning: 'to let', partOfSpeech: 'verb', hskLevel: 2, examples: ['请让我看看。(Please let me take a look.)'] },
  { characters: '日', pinyin: 'rì', meaning: 'day', partOfSpeech: 'noun', hskLevel: 2, examples: ['今天是几月几日？(What is the date today?)'] },
  { characters: '上班', pinyin: 'shàng bān', meaning: 'to go to work', partOfSpeech: 'verb', hskLevel: 2, examples: ['我每天八点上班。(I go to work at eight every day.)'] },
  { characters: '生病', pinyin: 'shēng bìng', meaning: 'to fall ill', partOfSpeech: 'verb', hskLevel: 2, examples: ['他生病了，不能来上课。(He is ill and cannot come to class.)'] },
  { characters: '时间', pinyin: 'shíjiān', meaning: 'time', partOfSpeech: 'noun', hskLevel: 2, examples: ['你有时间吗？(Do you have time?)'] },
  { characters: '事情', pinyin: 'shìqing', meaning: 'matter', partOfSpeech: 'noun', hskLevel: 2, examples: ['我有事情要做。(I have something to do.)'] },
  { characters: '手表', pinyin: 'shǒubiǎo', meaning: 'watch', partOfSpeech: 'noun', hskLevel: 2, examples: ['这块手表很贵。(This watch is very expensive.)'] },
  { characters: '说话', pinyin: 'shuō huà', meaning: 'to speak', partOfSpeech: 'verb', hskLevel: 2, examples: ['请不要大声说话。(Please do not speak loudly.)'] },
  { characters: '送', pinyin: 'sòng', meaning: 'to give', partOfSpeech: 'verb', hskLevel: 2, examples: ['我送你一本书。(I give you a book.)'] },
  { characters: '它', pinyin: 'tā', meaning: 'it', partOfSpeech: 'pronoun', hskLevel: 2, examples: ['这只猫很可爱，我喜欢它。(This cat is cute, I like it.)'] },
  { characters: '踢足球', pinyin: 'tī zúqiú', meaning: 'to play soccer', partOfSpeech: 'verb', hskLevel: 2, examples: ['我周末喜欢踢足球。(I like to play soccer on weekends.)'] },
  { characters: '题', pinyin: 'tí', meaning: 'question', partOfSpeech: 'noun', hskLevel: 2, examples: ['这个题很难。(This question is difficult.)'] },
  { characters: '跳舞', pinyin: 'tiào wǔ', meaning: 'to dance', partOfSpeech: 'verb', hskLevel: 2, examples: ['她喜欢跳舞。(She likes to dance.)'] },
  { characters: '外', pinyin: 'wài', meaning: 'outside', partOfSpeech: 'noun', hskLevel: 2, examples: ['我们去外面走走。(Let\'s go outside for a walk.)'] },
  { characters: '完', pinyin: 'wán', meaning: 'to finish', partOfSpeech: 'verb', hskLevel: 2, examples: ['我做完作业了。(I finished my homework.)'] },
  { characters: '玩', pinyin: 'wán', meaning: 'to play', partOfSpeech: 'verb', hskLevel: 2, examples: ['孩子们在公园里玩。(The children are playing in the park.)'] },
  { characters: '晚上', pinyin: 'wǎnshang', meaning: 'evening', partOfSpeech: 'noun', hskLevel: 2, examples: ['我们晚上去看电影。(We are going to watch a movie in the evening.)'] },
  { characters: '为什么', pinyin: 'wèishénme', meaning: 'why', partOfSpeech: 'adverb', hskLevel: 2, examples: ['你为什么不高兴？(Why are you unhappy?)'] },
  { characters: '问', pinyin: 'wèn', meaning: 'to ask', partOfSpeech: 'verb', hskLevel: 2, examples: ['我想问你一个问题。(I want to ask you a question.)'] },
  { characters: '问题', pinyin: 'wèntí', meaning: 'problem', partOfSpeech: 'noun', hskLevel: 2, examples: ['这个问题很简单。(This problem is very simple.)'] },
  { characters: '西瓜', pinyin: 'xīguā', meaning: 'watermelon', partOfSpeech: 'noun', hskLevel: 2, examples: ['夏天吃西瓜很舒服。(Eating watermelon in summer is very comfortable.)'] },
  { characters: '洗', pinyin: 'xǐ', meaning: 'to wash', partOfSpeech: 'verb', hskLevel: 2, examples: ['我每天洗衣服。(I wash clothes every day.)'] },
  { characters: '小时', pinyin: 'xiǎoshí', meaning: 'hour', partOfSpeech: 'noun', hskLevel: 2, examples: ['我等了两个小时。(I waited for two hours.)'] },
  { characters: '笑', pinyin: 'xiào', meaning: 'to smile', partOfSpeech: 'verb', hskLevel: 2, examples: ['她笑得很开心。(She smiles happily.)'] },
  { characters: '新', pinyin: 'xīn', meaning: 'new', partOfSpeech: 'adjective', hskLevel: 2, examples: ['我买了一辆新车。(I bought a new car.)'] },
  { characters: '姓', pinyin: 'xìng', meaning: 'surname', partOfSpeech: 'noun', hskLevel: 2, examples: ['我姓王。(My surname is Wang.)'] },
  { characters: '休息', pinyin: 'xiūxi', meaning: 'to rest', partOfSpeech: 'verb', hskLevel: 2, examples: ['我们休息一下吧。(Let\'s take a break.)'] },
  { characters: '雪', pinyin: 'xuě', meaning: 'snow', partOfSpeech: 'noun', hskLevel: 2, examples: ['下雪了，真漂亮。(It\'s snowing, it\'s really beautiful.)'] },
  { characters: '颜色', pinyin: 'yánsè', meaning: 'color', partOfSpeech: 'noun', hskLevel: 2, examples: ['你喜欢什么颜色？(What color do you like?)'] },
  { characters: '羊肉', pinyin: 'yángròu', meaning: 'mutton', partOfSpeech: 'noun', hskLevel: 2, examples: ['我不喜欢吃羊肉。(I don\'t like eating mutton.)'] },
  { characters: '药', pinyin: 'yào', meaning: 'medicine', partOfSpeech: 'noun', hskLevel: 2, examples: ['医生给我开了药。(The doctor prescribed me medicine.)'] },
  { characters: '要', pinyin: 'yào', meaning: 'to want', partOfSpeech: 'verb', hskLevel: 2, examples: ['我想要一杯水。(I want a glass of water.)'] },
  { characters: '也', pinyin: 'yě', meaning: 'also', partOfSpeech: 'adverb', hskLevel: 2, examples: ['我也喜欢看电影。(I also like watching movies.)'] },
  { characters: '一下', pinyin: 'yíxià', meaning: 'a bit', partOfSpeech: 'particle', hskLevel: 2, examples: ['请等一下。(Please wait a bit.)'] },
  { characters: '意思', pinyin: 'yìsi', meaning: 'meaning', partOfSpeech: 'noun', hskLevel: 2, examples: ['这个词是什么意思？(What does this word mean?)'] },
  { characters: '阴', pinyin: 'yīn', meaning: 'overcast', partOfSpeech: 'adjective', hskLevel: 2, examples: ['今天是阴天。(Today is an overcast day.)'] },
  { characters: '游泳', pinyin: 'yóuyǒng', meaning: 'to swim', partOfSpeech: 'verb', hskLevel: 2, examples: ['我喜欢在夏天游泳。(I like swimming in the summer.)'] },
  { characters: '右边', pinyin: 'yòubian', meaning: 'right side', partOfSpeech: 'noun', hskLevel: 2, examples: ['银行在学校的右边。(The bank is on the right side of the school.)'] },
  { characters: '鱼', pinyin: 'yú', meaning: 'fish', partOfSpeech: 'noun', hskLevel: 2, examples: ['我喜欢吃鱼。(I like eating fish.)'] },
  { characters: '运动', pinyin: 'yùndòng', meaning: 'sports', partOfSpeech: 'noun', hskLevel: 2, examples: ['我每天都做运动。(I do sports every day.)'] },
  { characters: '再', pinyin: 'zài', meaning: 'again', partOfSpeech: 'adverb', hskLevel: 2, examples: ['请再说一遍。(Please say it again.)'] },
  { characters: '早上', pinyin: 'zǎoshang', meaning: 'morning', partOfSpeech: 'noun', hskLevel: 2, examples: ['我早上六点起床。(I get up at six in the morning.)'] },
  { characters: '丈夫', pinyin: 'zhàngfu', meaning: 'husband', partOfSpeech: 'noun', hskLevel: 2, examples: ['她的丈夫很帅。(Her husband is handsome.)'] },
  { characters: '找', pinyin: 'zhǎo', meaning: 'to find', partOfSpeech: 'verb', hskLevel: 2, examples: ['我在找我的手机。(I am looking for my mobile phone.)'] },
  { characters: '着', pinyin: 'zhe', meaning: 'indicating action in progress', partOfSpeech: 'particle', hskLevel: 2, examples: ['他在看着书。(He is reading a book.)'] },
  { characters: '真', pinyin: 'zhēn', meaning: 'really', partOfSpeech: 'adverb', hskLevel: 2, examples: ['这个电影真好看。(This movie is really good.)'] },
  { characters: '正在', pinyin: 'zhèngzài', meaning: 'in the process of', partOfSpeech: 'adverb', hskLevel: 2, examples: ['我正在吃饭。(I am eating.)'] },
  { characters: '走', pinyin: 'zǒu', meaning: 'to walk', partOfSpeech: 'verb', hskLevel: 2, examples: ['我们走吧。(Let\'s go.)'] },
  { characters: '最', pinyin: 'zuì', meaning: 'most', partOfSpeech: 'adverb', hskLevel: 2, examples: ['他是我最好的朋友。(He is my best friend.)'] },
  { characters: '左边', pinyin: 'zuǒbian', meaning: 'left side', partOfSpeech: 'noun', hskLevel: 2, examples: ['银行在学校的左边。(The bank is on the left side of the school.)'] },

  // HSK 3 — 30 words
  { characters: '关系', pinyin: 'guān xì', meaning: 'Relationship / Connection', partOfSpeech: 'noun', hskLevel: 3, examples: ['没关系。(It doesn\'t matter / No worries.)'] },
  { characters: '环境', pinyin: 'huán jìng', meaning: 'Environment', partOfSpeech: 'noun', hskLevel: 3, examples: ['我们要保护环境。(We must protect the environment.)'] },
  { characters: '经验', pinyin: 'jīng yàn', meaning: 'Experience', partOfSpeech: 'noun', hskLevel: 3, examples: ['你有工作经验吗？(Do you have work experience?)'] },
  { characters: '机会', pinyin: 'jī huì', meaning: 'Opportunity / Chance', partOfSpeech: 'noun', hskLevel: 3, examples: ['这是一个好机会。(This is a good opportunity.)'] },
  { characters: '选择', pinyin: 'xuǎn zé', meaning: 'To choose / Choice', partOfSpeech: 'verb', hskLevel: 3, examples: ['你选择哪个？(Which one do you choose?)'] },
  { characters: '决定', pinyin: 'jué dìng', meaning: 'To decide / Decision', partOfSpeech: 'verb', hskLevel: 3, examples: ['我决定去中国。(I decided to go to China.)'] },
  { characters: '影响', pinyin: 'yǐng xiǎng', meaning: 'To influence / Influence', partOfSpeech: 'verb', hskLevel: 3, examples: ['天气影响了我的心情。(The weather influenced my mood.)'] },
  { characters: '比较', pinyin: 'bǐ jiào', meaning: 'Relatively / To compare', partOfSpeech: 'adverb', hskLevel: 3, examples: ['今天比较冷。(It\'s relatively cold today.)'] },
  { characters: '特别', pinyin: 'tè bié', meaning: 'Especially / Special', partOfSpeech: 'adverb', hskLevel: 3, examples: ['这道菜特别好吃。(This dish is especially delicious.)'] },
  { characters: '其实', pinyin: 'qí shí', meaning: 'Actually / In fact', partOfSpeech: 'adverb', hskLevel: 3, examples: ['其实我也不知道。(Actually, I don\'t know either.)'] },
  { characters: '终于', pinyin: 'zhōng yú', meaning: 'Finally / At last', partOfSpeech: 'adverb', hskLevel: 3, examples: ['我终于找到了！(I finally found it!)'] },
  { characters: '感觉', pinyin: 'gǎn jué', meaning: 'Feeling / To feel', partOfSpeech: 'noun', hskLevel: 3, examples: ['我感觉不太舒服。(I feel a bit unwell.)'] },
  { characters: '解决', pinyin: 'jiě jué', meaning: 'To solve / To resolve', partOfSpeech: 'verb', hskLevel: 3, examples: ['问题解决了。(The problem is solved.)'] },
  { characters: '讨论', pinyin: 'tǎo lùn', meaning: 'To discuss', partOfSpeech: 'verb', hskLevel: 3, examples: ['我们来讨论这个问题。(Let\'s discuss this issue.)'] },
  { characters: '练习', pinyin: 'liàn xí', meaning: 'To practice / Exercise', partOfSpeech: 'verb', hskLevel: 3, examples: ['多练习就会进步。(More practice leads to improvement.)'] },
  { characters: '提高', pinyin: 'tí gāo', meaning: 'To improve / To raise', partOfSpeech: 'verb', hskLevel: 3, examples: ['我要提高中文水平。(I want to improve my Chinese level.)'] },
  { characters: '接受', pinyin: 'jiē shòu', meaning: 'To accept', partOfSpeech: 'verb', hskLevel: 3, examples: ['我接受你的建议。(I accept your suggestion.)'] },
  { characters: '参加', pinyin: 'cān jiā', meaning: 'To participate / To join', partOfSpeech: 'verb', hskLevel: 3, examples: ['你要参加比赛吗？(Are you going to join the competition?)'] },
  { characters: '了解', pinyin: 'liǎo jiě', meaning: 'To understand / To know about', partOfSpeech: 'verb', hskLevel: 3, examples: ['我想了解中国文化。(I want to learn about Chinese culture.)'] },
  { characters: '注意', pinyin: 'zhù yì', meaning: 'To pay attention / Be careful', partOfSpeech: 'verb', hskLevel: 3, examples: ['请注意安全。(Please pay attention to safety.)'] },
  { characters: '打算', pinyin: 'dǎ suàn', meaning: 'To plan / To intend', partOfSpeech: 'verb', hskLevel: 3, examples: ['你打算什么时候去？(When do you plan to go?)'] },
  { characters: '根据', pinyin: 'gēn jù', meaning: 'According to / Based on', partOfSpeech: 'preposition', hskLevel: 3, examples: ['根据天气预报，明天会下雨。(According to the forecast, it will rain tomorrow.)'] },
  { characters: '或者', pinyin: 'huò zhě', meaning: 'Or (in statements)', partOfSpeech: 'conjunction', hskLevel: 3, examples: ['你可以坐公交或者地铁。(You can take the bus or the subway.)'] },
  { characters: '只要', pinyin: 'zhǐ yào', meaning: 'As long as', partOfSpeech: 'conjunction', hskLevel: 3, examples: ['只要努力就会成功。(As long as you work hard, you will succeed.)'] },
  { characters: '无论', pinyin: 'wú lùn', meaning: 'No matter / Regardless', partOfSpeech: 'conjunction', hskLevel: 3, examples: ['无论如何我都支持你。(No matter what, I support you.)'] },
  { characters: '态度', pinyin: 'tài dù', meaning: 'Attitude', partOfSpeech: 'noun', hskLevel: 3, examples: ['态度决定一切。(Attitude determines everything.)'] },
  { characters: '需要', pinyin: 'xū yào', meaning: 'To need / Needs', partOfSpeech: 'verb', hskLevel: 3, examples: ['我需要你的帮助。(I need your help.)'] },
  { characters: '应该', pinyin: 'yīng gāi', meaning: 'Should / Ought to', partOfSpeech: 'verb', hskLevel: 3, examples: ['你应该多休息。(You should rest more.)'] },
  { characters: '满意', pinyin: 'mǎn yì', meaning: 'Satisfied', partOfSpeech: 'adjective', hskLevel: 3, examples: ['我对结果很满意。(I\'m very satisfied with the result.)'] },
  { characters: '普通', pinyin: 'pǔ tōng', meaning: 'Ordinary / Common', partOfSpeech: 'adjective', hskLevel: 3, examples: ['我是一个普通人。(I\'m an ordinary person.)'] },

  // HSK 4 — 30 words
  { characters: '道歉', pinyin: 'dào qiàn', meaning: 'To apologize', partOfSpeech: 'verb', hskLevel: 4, examples: ['我应该向你道歉。(I should apologize to you.)'] },
  { characters: '建议', pinyin: 'jiàn yì', meaning: 'To suggest / Suggestion', partOfSpeech: 'verb', hskLevel: 4, examples: ['我建议你多运动。(I suggest you exercise more.)'] },
  { characters: '表达', pinyin: 'biǎo dá', meaning: 'To express', partOfSpeech: 'verb', hskLevel: 4, examples: ['我不知道怎么表达。(I don\'t know how to express it.)'] },
  { characters: '交流', pinyin: 'jiāo liú', meaning: 'To communicate / Exchange', partOfSpeech: 'verb', hskLevel: 4, examples: ['我们需要多交流。(We need to communicate more.)'] },
  { characters: '证明', pinyin: 'zhèng míng', meaning: 'To prove / Proof', partOfSpeech: 'verb', hskLevel: 4, examples: ['事实证明他是对的。(Facts proved he was right.)'] },
  { characters: '丰富', pinyin: 'fēng fù', meaning: 'Rich / Abundant', partOfSpeech: 'adjective', hskLevel: 4, examples: ['中国文化非常丰富。(Chinese culture is very rich.)'] },
  { characters: '复杂', pinyin: 'fù zá', meaning: 'Complex / Complicated', partOfSpeech: 'adjective', hskLevel: 4, examples: ['这个问题很复杂。(This problem is very complex.)'] },
  { characters: '骄傲', pinyin: 'jiāo ào', meaning: 'Proud / Pride', partOfSpeech: 'adjective', hskLevel: 4, examples: ['我为你感到骄傲。(I\'m proud of you.)'] },
  { characters: '积极', pinyin: 'jī jí', meaning: 'Active / Positive', partOfSpeech: 'adjective', hskLevel: 4, examples: ['要保持积极的态度。(Keep a positive attitude.)'] },
  { characters: '困难', pinyin: 'kùn nán', meaning: 'Difficulty / Difficult', partOfSpeech: 'adjective', hskLevel: 4, examples: ['别怕困难。(Don\'t be afraid of difficulties.)'] },
  { characters: '温柔', pinyin: 'wēn róu', meaning: 'Gentle / Tender', partOfSpeech: 'adjective', hskLevel: 4, examples: ['她很温柔。(She is very gentle.)'] },
  { characters: '诚实', pinyin: 'chéng shí', meaning: 'Honest', partOfSpeech: 'adjective', hskLevel: 4, examples: ['做人要诚实。(One should be honest.)'] },
  { characters: '感动', pinyin: 'gǎn dòng', meaning: 'To be moved / Touching', partOfSpeech: 'verb', hskLevel: 4, examples: ['这个故事很感动。(This story is very touching.)'] },
  { characters: '误会', pinyin: 'wù huì', meaning: 'Misunderstanding', partOfSpeech: 'noun', hskLevel: 4, examples: ['这是一个误会。(This is a misunderstanding.)'] },
  { characters: '效果', pinyin: 'xiào guǒ', meaning: 'Effect / Result', partOfSpeech: 'noun', hskLevel: 4, examples: ['效果很好。(The effect is very good.)'] },
  { characters: '即使', pinyin: 'jí shǐ', meaning: 'Even if', partOfSpeech: 'conjunction', hskLevel: 4, examples: ['即使失败也不放弃。(Even if I fail, I won\'t give up.)'] },
  { characters: '否则', pinyin: 'fǒu zé', meaning: 'Otherwise', partOfSpeech: 'conjunction', hskLevel: 4, examples: ['快点，否则会迟到。(Hurry up, otherwise we\'ll be late.)'] },
  { characters: '既然', pinyin: 'jì rán', meaning: 'Since / Now that', partOfSpeech: 'conjunction', hskLevel: 4, examples: ['既然来了，就留下吧。(Since you\'re here, stay.)'] },
  { characters: '尽管', pinyin: 'jǐn guǎn', meaning: 'Despite / Even though', partOfSpeech: 'conjunction', hskLevel: 4, examples: ['尽管很难，我也要试。(Despite the difficulty, I\'ll try.)'] },
  { characters: '原来', pinyin: 'yuán lái', meaning: 'Originally / So that\'s how it is', partOfSpeech: 'adverb', hskLevel: 4, examples: ['原来是你！(So it was you!)'] },
  { characters: '竟然', pinyin: 'jìng rán', meaning: 'Unexpectedly / To one\'s surprise', partOfSpeech: 'adverb', hskLevel: 4, examples: ['他竟然会说中文！(He can speak Chinese, surprisingly!)'] },
  { characters: '逐渐', pinyin: 'zhú jiàn', meaning: 'Gradually', partOfSpeech: 'adverb', hskLevel: 4, examples: ['天气逐渐变暖了。(The weather is gradually getting warmer.)'] },
  { characters: '幸福', pinyin: 'xìng fú', meaning: 'Happy / Blessed', partOfSpeech: 'adjective', hskLevel: 4, examples: ['祝你幸福！(Wishing you happiness!)'] },
  { characters: '勇敢', pinyin: 'yǒng gǎn', meaning: 'Brave / Courageous', partOfSpeech: 'adjective', hskLevel: 4, examples: ['你要勇敢面对。(You must bravely face it.)'] },
  { characters: '尊重', pinyin: 'zūn zhòng', meaning: 'To respect / Respect', partOfSpeech: 'verb', hskLevel: 4, examples: ['要尊重别人。(Respect others.)'] },
  { characters: '责任', pinyin: 'zé rèn', meaning: 'Responsibility', partOfSpeech: 'noun', hskLevel: 4, examples: ['这是我的责任。(This is my responsibility.)'] },
  { characters: '经济', pinyin: 'jīng jì', meaning: 'Economy / Economic', partOfSpeech: 'noun', hskLevel: 4, examples: ['中国经济发展很快。(China\'s economy is developing rapidly.)'] },
  { characters: '传统', pinyin: 'chuán tǒng', meaning: 'Tradition / Traditional', partOfSpeech: 'noun', hskLevel: 4, examples: ['这是中国的传统文化。(This is traditional Chinese culture.)'] },
  { characters: '暂时', pinyin: 'zàn shí', meaning: 'Temporarily', partOfSpeech: 'adverb', hskLevel: 4, examples: ['我暂时没有计划。(I don\'t have plans temporarily.)'] },
  { characters: '充分', pinyin: 'chōng fèn', meaning: 'Fully / Ample', partOfSpeech: 'adjective', hskLevel: 4, examples: ['做好充分的准备。(Be fully prepared.)'] },

  // HSK 5 — 30 words
  { characters: '辩论', pinyin: 'biàn lùn', meaning: 'To debate / Debate', partOfSpeech: 'verb', hskLevel: 5, examples: ['大学生辩论赛很精彩。(The university debate competition was brilliant.)'] },
  { characters: '沟通', pinyin: 'gōu tōng', meaning: 'To communicate', partOfSpeech: 'verb', hskLevel: 5, examples: ['有效沟通很重要。(Effective communication is important.)'] },
  { characters: '协调', pinyin: 'xié tiáo', meaning: 'To coordinate', partOfSpeech: 'verb', hskLevel: 5, examples: ['我来协调各方面。(I\'ll coordinate all aspects.)'] },
  { characters: '贡献', pinyin: 'gòng xiàn', meaning: 'Contribution / To contribute', partOfSpeech: 'noun', hskLevel: 5, examples: ['他做出了巨大贡献。(He made a huge contribution.)'] },
  { characters: '素质', pinyin: 'sù zhì', meaning: 'Quality / Caliber (of a person)', partOfSpeech: 'noun', hskLevel: 5, examples: ['提高个人素质很重要。(Improving personal quality is important.)'] },
  { characters: '弥补', pinyin: 'mí bǔ', meaning: 'To make up for / To compensate', partOfSpeech: 'verb', hskLevel: 5, examples: ['用行动弥补过错。(Make up for mistakes with actions.)'] },
  { characters: '独特', pinyin: 'dú tè', meaning: 'Unique / Distinctive', partOfSpeech: 'adjective', hskLevel: 5, examples: ['这个地方很独特。(This place is very unique.)'] },
  { characters: '显然', pinyin: 'xiǎn rán', meaning: 'Obviously / Evidently', partOfSpeech: 'adverb', hskLevel: 5, examples: ['显然他说的不对。(Obviously what he said is wrong.)'] },
  { characters: '深刻', pinyin: 'shēn kè', meaning: 'Profound / Deep', partOfSpeech: 'adjective', hskLevel: 5, examples: ['这本书意义深刻。(This book has profound meaning.)'] },
  { characters: '频繁', pinyin: 'pín fán', meaning: 'Frequent', partOfSpeech: 'adjective', hskLevel: 5, examples: ['最近加班太频繁了。(Overtime has been too frequent recently.)'] },
  { characters: '承担', pinyin: 'chéng dān', meaning: 'To bear / To undertake', partOfSpeech: 'verb', hskLevel: 5, examples: ['我愿意承担责任。(I\'m willing to bear the responsibility.)'] },
  { characters: '保持', pinyin: 'bǎo chí', meaning: 'To maintain / To keep', partOfSpeech: 'verb', hskLevel: 5, examples: ['保持冷静。(Stay calm.)'] },
  { characters: '促进', pinyin: 'cù jìn', meaning: 'To promote / To facilitate', partOfSpeech: 'verb', hskLevel: 5, examples: ['运动促进健康。(Exercise promotes health.)'] },
  { characters: '反映', pinyin: 'fǎn yìng', meaning: 'To reflect / To report', partOfSpeech: 'verb', hskLevel: 5, examples: ['这反映了社会问题。(This reflects social issues.)'] },
  { characters: '目前', pinyin: 'mù qián', meaning: 'At present / Currently', partOfSpeech: 'adverb', hskLevel: 5, examples: ['目前情况还不错。(The current situation is not bad.)'] },
  { characters: '合理', pinyin: 'hé lǐ', meaning: 'Reasonable / Rational', partOfSpeech: 'adjective', hskLevel: 5, examples: ['这个价格很合理。(This price is very reasonable.)'] },
  { characters: '灵活', pinyin: 'líng huó', meaning: 'Flexible / Agile', partOfSpeech: 'adjective', hskLevel: 5, examples: ['工作时间比较灵活。(Working hours are relatively flexible.)'] },
  { characters: '本质', pinyin: 'běn zhì', meaning: 'Essence / Nature', partOfSpeech: 'noun', hskLevel: 5, examples: ['问题的本质是什么？(What is the essence of the problem?)'] },
  { characters: '趋势', pinyin: 'qū shì', meaning: 'Trend / Tendency', partOfSpeech: 'noun', hskLevel: 5, examples: ['这是未来的趋势。(This is the trend of the future.)'] },
  { characters: '领域', pinyin: 'lǐng yù', meaning: 'Field / Domain', partOfSpeech: 'noun', hskLevel: 5, examples: ['他在科技领域很有名。(He is famous in the technology field.)'] },
  { characters: '具备', pinyin: 'jù bèi', meaning: 'To possess / To have', partOfSpeech: 'verb', hskLevel: 5, examples: ['他具备领导能力。(He possesses leadership ability.)'] },
  { characters: '克服', pinyin: 'kè fú', meaning: 'To overcome', partOfSpeech: 'verb', hskLevel: 5, examples: ['克服困难，继续前进。(Overcome difficulties and keep going.)'] },
  { characters: '恢复', pinyin: 'huī fù', meaning: 'To recover / To restore', partOfSpeech: 'verb', hskLevel: 5, examples: ['他已经恢复健康了。(He has recovered his health.)'] },
  { characters: '形成', pinyin: 'xíng chéng', meaning: 'To form / To take shape', partOfSpeech: 'verb', hskLevel: 5, examples: ['慢慢形成了习惯。(Gradually formed a habit.)'] },
  { characters: '实践', pinyin: 'shí jiàn', meaning: 'Practice / To put into practice', partOfSpeech: 'noun', hskLevel: 5, examples: ['理论要与实践结合。(Theory should combine with practice.)'] },
  { characters: '规模', pinyin: 'guī mó', meaning: 'Scale / Scope', partOfSpeech: 'noun', hskLevel: 5, examples: ['公司规模越来越大。(The company\'s scale is growing.)'] },
  { characters: '必然', pinyin: 'bì rán', meaning: 'Inevitable / Certainly', partOfSpeech: 'adverb', hskLevel: 5, examples: ['努力必然有回报。(Hard work inevitably pays off.)'] },
  { characters: '大概', pinyin: 'dà gài', meaning: 'Roughly / Probably', partOfSpeech: 'adverb', hskLevel: 5, examples: ['大概需要两个小时。(It takes roughly two hours.)'] },
  { characters: '从而', pinyin: 'cóng ér', meaning: 'Thereby / Thus', partOfSpeech: 'conjunction', hskLevel: 5, examples: ['努力学习，从而取得好成绩。(Study hard, thereby achieving good grades.)'] },
  { characters: '何况', pinyin: 'hé kuàng', meaning: 'Let alone / Not to mention', partOfSpeech: 'conjunction', hskLevel: 5, examples: ['大人都做不到，何况小孩。(Adults can\'t do it, let alone children.)'] },

  // HSK 6 — 30 words
  { characters: '抽象', pinyin: 'chōu xiàng', meaning: 'Abstract', partOfSpeech: 'adjective', hskLevel: 6, examples: ['这幅画很抽象。(This painting is very abstract.)'] },
  { characters: '含蓄', pinyin: 'hán xù', meaning: 'Implicit / Reserved', partOfSpeech: 'adjective', hskLevel: 6, examples: ['中国人表达感情比较含蓄。(Chinese people express feelings in a reserved way.)'] },
  { characters: '陌生', pinyin: 'mò shēng', meaning: 'Strange / Unfamiliar', partOfSpeech: 'adjective', hskLevel: 6, examples: ['我对这里很陌生。(I\'m very unfamiliar with this place.)'] },
  { characters: '微妙', pinyin: 'wēi miào', meaning: 'Subtle / Delicate', partOfSpeech: 'adjective', hskLevel: 6, examples: ['两人的关系很微妙。(The relationship between them is subtle.)'] },
  { characters: '渊博', pinyin: 'yuān bó', meaning: 'Erudite / Profound (knowledge)', partOfSpeech: 'adjective', hskLevel: 6, examples: ['他的知识非常渊博。(His knowledge is very profound.)'] },
  { characters: '憧憬', pinyin: 'chōng jǐng', meaning: 'To look forward to / Yearning', partOfSpeech: 'verb', hskLevel: 6, examples: ['她对未来充满憧憬。(She is full of yearning for the future.)'] },
  { characters: '揣摩', pinyin: 'chuǎi mó', meaning: 'To ponder / To try to figure out', partOfSpeech: 'verb', hskLevel: 6, examples: ['我在揣摩他的意思。(I\'m trying to figure out what he means.)'] },
  { characters: '陶醉', pinyin: 'táo zuì', meaning: 'To be intoxicated (with joy)', partOfSpeech: 'verb', hskLevel: 6, examples: ['她陶醉在音乐中。(She was intoxicated by the music.)'] },
  { characters: '领悟', pinyin: 'lǐng wù', meaning: 'To comprehend / To grasp', partOfSpeech: 'verb', hskLevel: 6, examples: ['我终于领悟了这个道理。(I finally grasped this truth.)'] },
  { characters: '钻研', pinyin: 'zuān yán', meaning: 'To study intensively / To delve into', partOfSpeech: 'verb', hskLevel: 6, examples: ['他钻研了多年。(He studied it intensively for many years.)'] },
  { characters: '洞察', pinyin: 'dòng chá', meaning: 'Insight / To see through', partOfSpeech: 'verb', hskLevel: 6, examples: ['他对人性有深刻的洞察。(He has profound insight into human nature.)'] },
  { characters: '弘扬', pinyin: 'hóng yáng', meaning: 'To promote / To carry forward', partOfSpeech: 'verb', hskLevel: 6, examples: ['弘扬传统文化。(Promote traditional culture.)'] },
  { characters: '典故', pinyin: 'diǎn gù', meaning: 'Classical allusion / Historical anecdote', partOfSpeech: 'noun', hskLevel: 6, examples: ['成语背后都有一个典故。(Every idiom has a classical allusion behind it.)'], notes: 'Commonly used when discussing the origin of Chinese idioms.' },
  { characters: '内涵', pinyin: 'nèi hán', meaning: 'Connotation / Inner meaning', partOfSpeech: 'noun', hskLevel: 6, examples: ['这首诗内涵丰富。(This poem has rich connotations.)'] },
  { characters: '素养', pinyin: 'sù yǎng', meaning: 'Cultivation / Accomplishment', partOfSpeech: 'noun', hskLevel: 6, examples: ['提高文化素养。(Improve cultural cultivation.)'] },
  { characters: '底蕴', pinyin: 'dǐ yùn', meaning: 'Cultural heritage / Inner depth', partOfSpeech: 'noun', hskLevel: 6, examples: ['这个城市有深厚的文化底蕴。(This city has deep cultural heritage.)'] },
  { characters: '格局', pinyin: 'gé jú', meaning: 'Pattern / Layout / Vision', partOfSpeech: 'noun', hskLevel: 6, examples: ['要有大格局。(One should have a big-picture vision.)'] },
  { characters: '境界', pinyin: 'jìng jiè', meaning: 'Realm / Level of attainment', partOfSpeech: 'noun', hskLevel: 6, examples: ['这是人生的最高境界。(This is the highest realm of life.)'] },
  { characters: '精髓', pinyin: 'jīng suǐ', meaning: 'Essence / Quintessence', partOfSpeech: 'noun', hskLevel: 6, examples: ['学到了中国文化的精髓。(Learned the essence of Chinese culture.)'] },
  { characters: '渊源', pinyin: 'yuān yuán', meaning: 'Origin / Deep-rooted connection', partOfSpeech: 'noun', hskLevel: 6, examples: ['两国有深厚的历史渊源。(The two countries have deep historical connections.)'] },
  { characters: '隐喻', pinyin: 'yǐn yù', meaning: 'Metaphor', partOfSpeech: 'noun', hskLevel: 6, examples: ['成语常用隐喻的手法。(Idioms often use metaphorical techniques.)'] },
  { characters: '博大精深', pinyin: 'bó dà jīng shēn', meaning: 'Broad and profound', partOfSpeech: 'adjective', hskLevel: 6, examples: ['中国文化博大精深。(Chinese culture is broad and profound.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '融会贯通', pinyin: 'róng huì guàn tōng', meaning: 'To master thoroughly through understanding', partOfSpeech: 'verb', hskLevel: 6, examples: ['学习要融会贯通。(Learning should involve thorough understanding.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '源远流长', pinyin: 'yuán yuǎn liú cháng', meaning: 'Having a long history', partOfSpeech: 'adjective', hskLevel: 6, examples: ['中国文化源远流长。(Chinese culture has a long history.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '耐人寻味', pinyin: 'nài rén xún wèi', meaning: 'Thought-provoking / Worth pondering', partOfSpeech: 'adjective', hskLevel: 6, examples: ['这个故事耐人寻味。(This story is thought-provoking.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '潜移默化', pinyin: 'qián yí mò huà', meaning: 'To influence subtly / Imperceptible influence', partOfSpeech: 'verb', hskLevel: 6, examples: ['文化潜移默化地影响人们。(Culture subtly influences people.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '与日俱增', pinyin: 'yǔ rì jù zēng', meaning: 'Increasing day by day', partOfSpeech: 'verb', hskLevel: 6, examples: ['学中文的人与日俱增。(The number of people learning Chinese is increasing day by day.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '举一反三', pinyin: 'jǔ yī fǎn sān', meaning: 'To infer many things from one case', partOfSpeech: 'verb', hskLevel: 6, examples: ['学习要举一反三。(When learning, one should infer many things from one case.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '循序渐进', pinyin: 'xún xù jiàn jìn', meaning: 'Step by step / Progressing in order', partOfSpeech: 'adverb', hskLevel: 6, examples: ['学习语言要循序渐进。(Learning a language should progress step by step.)'], notes: 'This is itself an idiom (chengyu)!' },
  { characters: '独树一帜', pinyin: 'dú shù yī zhì', meaning: 'To stand out / Unique style', partOfSpeech: 'verb', hskLevel: 6, examples: ['他的写作风格独树一帜。(His writing style is truly unique.)'], notes: 'This is itself an idiom (chengyu)!' },
];

// Exam prep data — real exam formats from official HSK guidelines
export const HSK_EXAM_INFO: Record<number, {
  totalQuestions: number;
  duration: string;
  passingScore: string;
  totalPoints: number;
  sections: { name: string; questions: number; duration: string; tips: string }[];
  studyTips: string[];
  vocabRequired: string;
} | null> = {
  1: {
    totalQuestions: 40,
    duration: '40 minutes',
    passingScore: '120 / 200',
    totalPoints: 200,
    sections: [
      { name: 'Listening', questions: 20, duration: '15 min', tips: 'Short phrases and sentences are played twice. Focus on understanding basic greetings, numbers, dates, and simple questions about daily life.' },
      { name: 'Reading', questions: 20, duration: '17 min', tips: 'Match pictures with words, fill in blanks with pinyin clues. Practice recognizing the 143 HSK 1 characters quickly — speed matters more than deep understanding at this level.' },
    ],
    studyTips: [
      'Focus on the most common 143 words first — recognition is more important than writing at HSK 1.',
      'Practice listening to simple Chinese daily, even just 10 minutes. Try slow-speed HSK 1 practice audio.',
      'Learn pinyin thoroughly — it\'s the foundation for all pronunciation and helps with reading questions.',
      'Use flashcards with pictures. Visual association helps remember characters at the beginner stage.',
      'Practice number recognition (1-99) and basic time expressions — they appear frequently on the exam.',
    ],
    vocabRequired: '143 words',
  },
  2: {
    totalQuestions: 60,
    duration: '55 minutes',
    passingScore: '120 / 200',
    totalPoints: 200,
    sections: [
      { name: 'Listening', questions: 35, duration: '25 min', tips: 'Dialogues about shopping, transportation, and daily routines. Questions are played twice. Listen for key words like prices, times, and locations.' },
      { name: 'Reading', questions: 25, duration: '22 min', tips: 'Match sentences with pictures, judge true/false statements, and fill in blanks. Read the full sentence before choosing — context clues are essential at this level.' },
    ],
    studyTips: [
      'Build on HSK 1 vocabulary — HSK 2 adds 148 new words focused on daily life situations.',
      'Practice basic sentence patterns: 因为...所以..., 虽然...但是..., 比 comparisons.',
      'Listen to short dialogues about shopping, directions, and weather — these are the most common HSK 2 topics.',
      'Learn to express time sequences: 先...然后..., 以前, 以后, 的时候.',
      'Practice reading short sentences quickly — the reading section requires good time management.',
    ],
    vocabRequired: '148 words (291 cumulative)',
  },
  3: {
    totalQuestions: 80,
    duration: '90 minutes',
    passingScore: '180 / 300',
    totalPoints: 300,
    sections: [
      { name: 'Listening', questions: 40, duration: '35 min', tips: 'Focus on understanding short dialogues about daily life. Questions increase in length — practice with real HSK audio at 1x speed.' },
      { name: 'Reading', questions: 30, duration: '30 min', tips: 'Match sentences, fill in blanks, and read short paragraphs. Time management is key — skip questions you\'re stuck on and come back.' },
      { name: 'Writing', questions: 10, duration: '15 min', tips: 'Rearrange words into correct sentences. Practice common sentence patterns like 把 (bǎ) and 被 (bèi) constructions.' },
    ],
    studyTips: [
      'Master all 600 vocabulary words — flashcards with spaced repetition (Anki) work well at this level.',
      'Practice the 把 construction and 被 passive voice — they appear frequently in reading and writing.',
      'Listen to short Chinese podcasts or HSK 3 listening practice daily for at least 15 minutes.',
      'Write out sentences by hand — the writing section tests sentence construction, not free writing.',
    ],
    vocabRequired: '600 words',
  },
  4: {
    totalQuestions: 100,
    duration: '105 minutes',
    passingScore: '180 / 300',
    totalPoints: 300,
    sections: [
      { name: 'Listening', questions: 45, duration: '30 min', tips: 'Dialogues get longer and more natural. You\'ll hear conversations about work, social situations, and current events. Practice listening without reading transcripts first.' },
      { name: 'Reading', questions: 40, duration: '40 min', tips: 'Includes fill-in-the-blank, sentence ordering, and passage comprehension. Read the questions before the passage to save time. Look for context clues in surrounding sentences.' },
      { name: 'Writing', questions: 15, duration: '25 min', tips: 'Write sentences using given words, and describe a picture in 80+ characters. Practice writing short paragraphs about daily topics — focus on correct grammar over complex vocabulary.' },
    ],
    studyTips: [
      'HSK 4 is the biggest jump in difficulty. Budget 3-6 months of focused study if you passed HSK 3 recently.',
      'Read Chinese news headlines daily (try The Chairman\'s Bao or Du Chinese app) — HSK 4 reading passages mirror news style.',
      'Master complement structures (结果补语, 趋向补语) — they\'re tested heavily in both reading and writing.',
      'Practice writing 80-character paragraphs from picture prompts. Time yourself — you only get 25 minutes for the whole writing section.',
      'Watch Chinese shows with Chinese subtitles (not English). This builds reading speed and listening comprehension simultaneously.',
    ],
    vocabRequired: '1,200 words',
  },
  5: {
    totalQuestions: 100,
    duration: '125 minutes',
    passingScore: '180 / 300',
    totalPoints: 300,
    sections: [
      { name: 'Listening', questions: 45, duration: '30 min', tips: 'Includes longer monologues and interviews. Speakers talk at natural speed with colloquialisms. Practice with Chinese podcasts, news broadcasts, and TED talks in Chinese.' },
      { name: 'Reading', questions: 45, duration: '45 min', tips: 'Passages are 300-500 characters long, covering society, culture, science, and business. You need strong scanning skills — practice reading full articles in under 3 minutes.' },
      { name: 'Writing', questions: 10, duration: '40 min', tips: 'Write an essay of 80+ characters from keywords AND rewrite a passage from memory after reading it for 10 minutes. The rewrite is the hardest part — practice summarizing articles in your own words.' },
    ],
    studyTips: [
      'Read at least one full Chinese article daily — newspapers (人民日报), magazines, or graded readers at HSK 5 level.',
      'The passage-rewrite task is unique to HSK 5. Practice by reading a paragraph, closing it, and rewriting the key points from memory.',
      'Learn formal written Chinese (书面语) — HSK 5 tests written register, which differs from spoken Mandarin.',
      'Study idioms (成语) seriously — they appear in reading passages and are expected in writing at this level.',
      'Practice writing essays with clear structure: opening statement, 2-3 supporting points, conclusion. Chinese essay structure favors directness.',
      'Take full-length practice tests under timed conditions at least twice before your exam date.',
    ],
    vocabRequired: '2,500 words',
  },
  6: {
    totalQuestions: 101,
    duration: '140 minutes',
    passingScore: '180 / 300',
    totalPoints: 300,
    sections: [
      { name: 'Listening', questions: 50, duration: '35 min', tips: 'Native-speed conversations, lectures, and news broadcasts. Focus on understanding tone, implication, and speaker attitude — not just literal meaning.' },
      { name: 'Reading', questions: 50, duration: '50 min', tips: 'Includes texts with classical Chinese references and academic vocabulary. Speed is critical — practice reading 500+ character passages and answering questions in under 5 minutes.' },
      { name: 'Writing', questions: 1, duration: '45 min', tips: 'Write a 400-character essay summarizing a 1000-character passage read for 10 minutes. Structure your summary clearly: main argument, key evidence, conclusion.' },
    ],
    studyTips: [
      'At HSK 6, immersion is essential. Consume Chinese media daily — news, podcasts, books, social media.',
      'The writing section requires summarizing a long passage from memory. Practice by reading opinion articles and writing 400-character summaries.',
      'Learn to identify rhetorical devices and literary allusions — they appear in both reading and listening.',
      'Study classical Chinese (文言文) basics — HSK 6 reading occasionally includes classical references.',
      'Practice speed reading: aim to read 200+ characters per minute with 80%+ comprehension.',
    ],
    vocabRequired: '5,000+ words',
  },
};

// Listicle slugs related to each HSK level
export const HSK_LISTICLES: Record<number, { slug: string; title: string }[]> = {
  1: [],
  2: [],
  3: [
    { slug: 'chinese-idioms-hsk-3', title: '10 Simple Chinese Idioms for HSK 3 Learners' },
  ],
  4: [
    { slug: 'chinese-idioms-hsk-4', title: '12 Essential Chinese Idioms for HSK 4 Learners' },
    { slug: 'chinese-idioms-hsk-4-advanced', title: '12 More Chinese Idioms for HSK 4 Practice' },
  ],
  5: [
    { slug: 'chinese-idioms-hsk-5', title: '12 Advanced Chinese Idioms for HSK 5 Learners' },
    { slug: 'chinese-idioms-hsk-5-reading', title: 'Chinese Idioms for HSK 5 Reading Comprehension' },
  ],
  6: [
    { slug: 'chinese-idioms-hsk-6', title: '12 Sophisticated Chinese Idioms for HSK 6 Mastery' },
    { slug: 'chinese-idioms-hsk-6-writing', title: 'Chinese Idioms for HSK 6 Writing' },
    { slug: 'chinese-idioms-hsk-7-9', title: 'Chinese Idioms for HSK 7-9 (New HSK)' },
  ],
};

// Helper functions
export function getAllHSKEntries(): HSKEntry[] {
  return hskEntries;
}

export function getHSKByLevel(level: number): HSKEntry[] {
  return hskEntries.filter(e => e.hskLevel === level);
}

export function loadTranslatedHSK(lang: string): TranslatedHSKEntry[] {
  try {
    const filePath = path.join(process.cwd(), 'public', 'translations', lang, 'hsk.json');
    const data = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(data) as TranslatedHSKEntry[];
  } catch {
    // Fallback to English if translation doesn't exist
    return hskEntries.map(entry => ({
      ...entry,
      originalMeaning: entry.meaning,
    }));
  }
}

export function getTranslatedHSKByLevel(level: number, lang: string): TranslatedHSKEntry[] {
  const entries = loadTranslatedHSK(lang);
  return entries.filter(e => e.hskLevel === level);
}
