import fs from 'fs';
import path from 'path';

export type PhraseTerm = {
  slug: string;
  characters: string;
  pinyin: string;
  meaning: string;
  context: string;
  examples: string[];
  category: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  formality: 'casual' | 'neutral' | 'formal';
};

export type TranslatedPhraseTerm = PhraseTerm & {
  originalSlug: string;
};

export const PHRASE_CATEGORIES = [
  'Restaurant & Food',
  'Shopping & Bargaining',
  'Getting Around',
  'Making Plans & Socializing',
  'Reactions & Opinions',
  'Work & Professional',
  'Emergencies & Help',
  'Daily Life & Feelings',
] as const;

export const phraseTerms: PhraseTerm[] = [
  // ===== Restaurant & Food =====
  {
    slug: 'mai-dan',
    characters: '买单',
    pinyin: 'mǎi dān',
    meaning: 'Check please / pay the bill',
    context: 'Used at the end of a meal to signal you want to pay. Just raise your hand and say this to the waiter. In some regions, 结账 (jié zhàng) is used instead.',
    examples: [
      '服务员，买单！(Waiter, check please!)',
      'Can we 买单? We\'re ready to go.',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'da-bao',
    characters: '打包',
    pinyin: 'dǎ bāo',
    meaning: 'To-go box / doggy bag / pack it up',
    context: 'Used when you have leftover food and want to take it home. Very common and not considered rude at all in China — wasting food is worse.',
    examples: [
      '这个菜打包吧。(Let\'s pack up this dish.)',
      '可以打包吗？(Can I get this to go?)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'bu-yao-la',
    characters: '不要辣',
    pinyin: 'bù yào là',
    meaning: 'No spice / not spicy please',
    context: 'Essential survival phrase in Sichuan, Hunan, and other spice-heavy regions. Variations: 少辣 (shǎo là, less spicy), 微辣 (wēi là, mild spice), 中辣 (zhōng là, medium).',
    examples: [
      '不要辣，谢谢。(No spice, thanks.)',
      '我不能吃辣，少辣可以吗？(I can\'t eat spicy, can you make it less spicy?)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'you-shen-me-tui-jian',
    characters: '有什么推荐',
    pinyin: 'yǒu shén me tuī jiàn',
    meaning: 'What do you recommend?',
    context: 'Great way to discover local specialties. Restaurant staff usually love recommending their signature dishes. Can also be used at shops or cafes.',
    examples: [
      '你们这儿有什么推荐？(What do you recommend here?)',
      '第一次来，有什么推荐的菜？(First time here, any dish recommendations?)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'wo-chi-su',
    characters: '我吃素',
    pinyin: 'wǒ chī sù',
    meaning: 'I\'m vegetarian / I eat vegetarian food',
    context: 'Important for vegetarians dining out. Note that "vegetarian" in China may still include egg and dairy. For vegan, say 我是纯素 (wǒ shì chún sù).',
    examples: [
      '我吃素，有素菜吗？(I\'m vegetarian, do you have vegetable dishes?)',
      '这个里面有肉吗？我吃素。(Does this have meat? I\'m vegetarian.)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'gan-bei',
    characters: '干杯',
    pinyin: 'gān bēi',
    meaning: 'Cheers! / Bottoms up!',
    context: 'Literally "dry cup" — means to finish your drink in one go. At formal dinners, you may hear this many times. You can also say 随意 (suí yì, drink at your own pace) if you can\'t keep up.',
    examples: [
      '为我们的友谊干杯！(Cheers to our friendship!)',
      '来，干杯！(Come on, bottoms up!)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'zai-lai-yi-ge',
    characters: '再来一个',
    pinyin: 'zài lái yī gè',
    meaning: 'One more / another one please',
    context: 'Used to order another dish, drink, or portion. Works in restaurants, bars, and street food stalls.',
    examples: [
      '这个很好吃，再来一个！(This is delicious, one more please!)',
      '啤酒再来一个。(Another beer please.)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'chi-bao-le',
    characters: '吃饱了',
    pinyin: 'chī bǎo le',
    meaning: 'I\'m full / I\'ve had enough to eat',
    context: 'Polite way to decline more food. In Chinese culture, hosts will keep offering food. Saying 吃饱了 shows appreciation while indicating you\'ve had plenty.',
    examples: [
      '谢谢，我吃饱了。(Thanks, I\'m full.)',
      '真的吃饱了，不用再加了。(I\'m really full, no need to add more.)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'aa-zhi',
    characters: 'AA制',
    pinyin: 'AA zhì',
    meaning: 'Split the bill / go Dutch',
    context: 'Common among friends and younger people. In traditional Chinese culture, one person usually pays for the whole table, but AA制 is becoming more accepted especially among millennials.',
    examples: [
      '今天AA制吧。(Let\'s split the bill today.)',
      '我们AA还是你请？(Are we splitting or are you treating?)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'intermediate',
    formality: 'casual',
  },
  {
    slug: 'zhe-ge-zen-me-chi',
    characters: '这个怎么吃',
    pinyin: 'zhè ge zěn me chī',
    meaning: 'How do you eat this?',
    context: 'Useful when facing unfamiliar Chinese dishes like hotpot, Peking duck wraps, or xiaolongbao. No one will judge you for asking — it shows genuine interest.',
    examples: [
      '这个怎么吃？要蘸酱吗？(How do you eat this? Do I dip it in sauce?)',
      '小笼包怎么吃才不会烫？(How do you eat xiaolongbao without burning yourself?)',
    ],
    category: 'Restaurant & Food',
    difficulty: 'beginner',
    formality: 'neutral',
  },

  // ===== Shopping & Bargaining =====
  {
    slug: 'tai-gui-le',
    characters: '太贵了',
    pinyin: 'tài guì le',
    meaning: 'Too expensive!',
    context: 'The essential phrase for bargaining in markets. Say this with a slightly pained expression for maximum effect. Works in markets, small shops, and with street vendors — not in malls or chain stores.',
    examples: [
      '太贵了，便宜点吧！(Too expensive, make it cheaper!)',
      '这个太贵了，我再看看。(This is too expensive, I\'ll look around more.)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'pian-yi-dian',
    characters: '便宜点',
    pinyin: 'pián yi diǎn',
    meaning: 'A little cheaper please / give me a discount',
    context: 'The follow-up to 太贵了. A polite way to open negotiations. Can be combined with reasons like buying multiple items or being a regular customer.',
    examples: [
      '老板，便宜点嘛！(Boss, give me a better price!)',
      '买两个能便宜点吗？(Can it be cheaper if I buy two?)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'ke-yi-shi-shi-ma',
    characters: '可以试试吗',
    pinyin: 'kě yǐ shì shì ma',
    meaning: 'Can I try it on / Can I try it?',
    context: 'Used in clothing stores, shoe shops, or when sampling food. Most shops will let you try things on, though some market stalls may not.',
    examples: [
      '这件衣服可以试试吗？(Can I try on this piece of clothing?)',
      '这个口味可以试试吗？(Can I try this flavor?)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'you-mei-you-bie-de-yan-se',
    characters: '有没有别的颜色',
    pinyin: 'yǒu méi yǒu bié de yán sè',
    meaning: 'Do you have other colors?',
    context: 'Useful when shopping for clothing, accessories, or home items. You can substitute 颜色 with 尺码 (chǐ mǎ, size) or 款式 (kuǎn shì, style).',
    examples: [
      '这个有没有别的颜色？(Does this come in other colors?)',
      '有没有大一号的？(Do you have one size bigger?)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'intermediate',
    formality: 'neutral',
  },
  {
    slug: 'shua-ka-hai-shi-xian-jin',
    characters: '刷卡还是现金',
    pinyin: 'shuā kǎ hái shì xiàn jīn',
    meaning: 'Card or cash?',
    context: 'You\'ll hear this at checkout. Nowadays most places also accept WeChat Pay and Alipay. You might also hear 微信还是支付宝 (WeChat or Alipay?).',
    examples: [
      '刷卡还是现金？——微信支付可以吗？(Card or cash?——Can I use WeChat Pay?)',
      '可以刷卡吗？(Can I pay by card?)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'da-zhe',
    characters: '打折',
    pinyin: 'dǎ zhé',
    meaning: 'Discount / on sale',
    context: 'In China, discounts are expressed as the fraction you pay: 打八折 means 80% of the price (20% off), 打五折 means 50% off. This is the opposite of how discounts work in English.',
    examples: [
      '现在打折吗？(Is there a discount now?)',
      '这个打几折？(What\'s the discount on this?)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'intermediate',
    formality: 'neutral',
  },
  {
    slug: 'jia-de-ba',
    characters: '假的吧',
    pinyin: 'jiǎ de ba',
    meaning: 'Is this fake? / No way!',
    context: 'Used when questioning authenticity of products in markets, or as an expression of disbelief in conversation. In shopping contexts, be careful using this too aggressively.',
    examples: [
      '这个是真的还是假的？(Is this real or fake?)',
      '五百块？假的吧！(500 yuan? No way!)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'intermediate',
    formality: 'casual',
  },
  {
    slug: 'bao-you-ma',
    characters: '包邮吗',
    pinyin: 'bāo yóu ma',
    meaning: 'Does it include free shipping?',
    context: 'Essential for online shopping on Taobao, JD.com, etc. One of the first things Chinese shoppers ask. Can also be used jokingly in person.',
    examples: [
      '这个包邮吗？(Does this include free shipping?)',
      '满多少包邮？(How much do I need to spend for free shipping?)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'intermediate',
    formality: 'casual',
  },
  {
    slug: 'tui-huo',
    characters: '退货',
    pinyin: 'tuì huò',
    meaning: 'Return a product / refund',
    context: 'Used when you want to return something you bought. 退款 (tuì kuǎn) specifically means refund of money. Online shopping platforms usually have a 7-day return policy.',
    examples: [
      '这个可以退货吗？(Can I return this?)',
      '我想退货退款。(I want to return this for a refund.)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'intermediate',
    formality: 'neutral',
  },
  {
    slug: 'zui-di-duo-shao',
    characters: '最低多少',
    pinyin: 'zuì dī duō shǎo',
    meaning: 'What\'s the lowest price? / What\'s your best offer?',
    context: 'The power move in bargaining. Use this after going back and forth a few times. It signals you\'re serious about buying but need a better price.',
    examples: [
      '最低多少钱？(What\'s the absolute lowest price?)',
      '不用讲价了，最低多少？(No more negotiating, what\'s your bottom price?)',
    ],
    category: 'Shopping & Bargaining',
    difficulty: 'intermediate',
    formality: 'casual',
  },

  // ===== Getting Around =====
  {
    slug: 'zen-me-zou',
    characters: '怎么走',
    pinyin: 'zěn me zǒu',
    meaning: 'How do I get there? / Which way?',
    context: 'The most basic direction-asking phrase. Point at a map or mention a landmark, then ask 怎么走. People will usually point you in the right direction even with a language barrier.',
    examples: [
      '请问，地铁站怎么走？(Excuse me, how do I get to the subway station?)',
      '去天安门怎么走？(How do I get to Tiananmen?)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'dao-le-ma',
    characters: '到了吗',
    pinyin: 'dào le ma',
    meaning: 'Are we there yet? / Have we arrived?',
    context: 'Used in taxis, buses, or when someone is driving you. You can also ask the driver 快到了吗 (kuài dào le ma, are we almost there?).',
    examples: [
      '师傅，到了吗？(Driver, are we there?)',
      '还没到吗？还有多远？(Haven\'t we arrived yet? How much further?)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'zai-na-li-xia-che',
    characters: '在哪里下车',
    pinyin: 'zài nǎ lǐ xià chē',
    meaning: 'Where do I get off?',
    context: 'Used on buses and subways. Show the driver or a fellow passenger your destination on your phone and ask this. On buses, the driver or automated announcements will call out stops.',
    examples: [
      '请问，去故宫在哪里下车？(Excuse me, where do I get off for the Forbidden City?)',
      '我应该在哪一站下车？(Which stop should I get off at?)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'du-che-le',
    characters: '堵车了',
    pinyin: 'dǔ chē le',
    meaning: 'There\'s a traffic jam / stuck in traffic',
    context: 'Very common in Chinese cities, especially during rush hour. Taxi drivers will often mention this proactively. A useful excuse for being late too.',
    examples: [
      '不好意思，堵车了，可能要迟到。(Sorry, stuck in traffic, might be late.)',
      '这条路总是堵车。(This road always has traffic jams.)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'shi-fu-ting-yi-xia',
    characters: '师傅停一下',
    pinyin: 'shī fu tíng yī xià',
    meaning: 'Driver, please stop here',
    context: 'Used in taxis and ride-shares when you want to be dropped off. 师傅 (shī fu) is the respectful way to address a driver. You can also say 前面停 (qián miàn tíng, stop up ahead).',
    examples: [
      '师傅，前面路口停一下。(Driver, please stop at the intersection ahead.)',
      '师傅，就这里停吧。(Driver, you can stop right here.)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'mi-lu-le',
    characters: '迷路了',
    pinyin: 'mí lù le',
    meaning: 'I\'m lost',
    context: 'Show someone your phone with the destination on a map and say this. Most Chinese people will go out of their way to help you find your way, sometimes even walking you there.',
    examples: [
      '不好意思，我迷路了。(Excuse me, I\'m lost.)',
      '我迷路了，这里是哪儿？(I\'m lost, where is this?)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'you-wifi-ma',
    characters: '有Wi-Fi吗',
    pinyin: 'yǒu Wi-Fi ma',
    meaning: 'Do you have Wi-Fi?',
    context: 'Essential for travelers. Most cafes, restaurants, and hotels have Wi-Fi. The password is often displayed on a sign or you can ask: 密码是什么 (mì mǎ shì shén me, what\'s the password?).',
    examples: [
      '请问有Wi-Fi吗？密码是多少？(Do you have Wi-Fi? What\'s the password?)',
      '这里Wi-Fi信号好吗？(Is the Wi-Fi signal good here?)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'duo-jiu-neng-dao',
    characters: '多久能到',
    pinyin: 'duō jiǔ néng dào',
    meaning: 'How long until we arrive? / How long does it take?',
    context: 'Used in taxis, with ride-share drivers, or when asking about transit times. Also works for delivery estimates and meeting up with friends.',
    examples: [
      '师傅，多久能到？(Driver, how long until we get there?)',
      '坐地铁多久能到？(How long does it take by subway?)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'jin-bu-jin',
    characters: '近不近',
    pinyin: 'jìn bù jìn',
    meaning: 'Is it nearby? / Is it close?',
    context: 'A quick way to gauge distance before committing to walking somewhere. The answer is often 很近 (hěn jìn, very close) or 不远 (bù yuǎn, not far) — though Chinese definitions of "close" can vary wildly.',
    examples: [
      '地铁站近不近？(Is the subway station nearby?)',
      '走路去近不近？(Is it close enough to walk?)',
    ],
    category: 'Getting Around',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'dao-hang',
    characters: '导航',
    pinyin: 'dǎo háng',
    meaning: 'GPS navigation / use the map app',
    context: 'Tell a taxi driver to follow the GPS, or ask someone to help you navigate. 高德地图 (Gaode/Amap) and 百度地图 (Baidu Maps) are the main navigation apps in China.',
    examples: [
      '师傅，你开导航吧。(Driver, just follow the GPS.)',
      '我导航一下。(Let me check the navigation.)',
    ],
    category: 'Getting Around',
    difficulty: 'intermediate',
    formality: 'neutral',
  },

  // ===== Making Plans & Socializing =====
  {
    slug: 'you-kong-ma',
    characters: '有空吗',
    pinyin: 'yǒu kòng ma',
    meaning: 'Are you free? / Do you have time?',
    context: 'The standard way to invite someone out. Usually followed by a specific plan. Can be used for today or a future date — add a time word like 明天 (míng tiān, tomorrow) or 周末 (zhōu mò, weekend).',
    examples: [
      '周末有空吗？一起吃饭？(Are you free this weekend? Wanna eat together?)',
      '你明天有空吗？(Are you free tomorrow?)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'gai-tian-ba',
    characters: '改天吧',
    pinyin: 'gǎi tiān ba',
    meaning: 'Another day / Let\'s do it some other time',
    context: 'A polite way to decline an invitation without flat-out saying no. In Chinese social culture, this is a soft rejection that saves face for both parties.',
    examples: [
      '今天太忙了，改天吧。(Too busy today, let\'s do it another day.)',
      '改天再约吧。(Let\'s arrange it for another time.)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'sui-bian',
    characters: '随便',
    pinyin: 'suí biàn',
    meaning: 'Whatever / anything is fine / I don\'t mind',
    context: 'The most common (and sometimes frustrating) answer when making plans. Used when you genuinely don\'t have a preference. Warning: saying 随便 too much can seem indifferent.',
    examples: [
      '吃什么？——随便，都行。(What do you want to eat?——Whatever, anything is fine.)',
      '你随便选吧。(You just pick whatever.)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'kan-ni',
    characters: '看你',
    pinyin: 'kàn nǐ',
    meaning: 'Up to you / your call',
    context: 'Deferring the decision to the other person. Similar to 随便 but puts the responsibility on the other person. Common when friends are deciding where to eat, what to do, etc.',
    examples: [
      '去哪儿？——看你。(Where should we go?——Up to you.)',
      '想看什么电影？看你吧。(What movie do you want to watch? Your call.)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'suan-le-phrase',
    characters: '算了',
    pinyin: 'suàn le',
    meaning: 'Forget it / never mind',
    context: 'Used when giving up on a plan, dropping an argument, or deciding something isn\'t worth the effort. Can express mild frustration or acceptance.',
    examples: [
      '等了半小时了，算了，走吧。(Waited half an hour, forget it, let\'s go.)',
      '算了算了，不想了。(Forget it, forget it, I don\'t want to think about it.)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'wu-suo-wei',
    characters: '无所谓',
    pinyin: 'wú suǒ wèi',
    meaning: 'I don\'t care / it doesn\'t matter',
    context: 'Stronger than 随便. Can sound apathetic or genuinely easy-going depending on tone. Use carefully — with wrong tone it can come across as dismissive.',
    examples: [
      '你迟到了！——无所谓，我也没事。(You\'re late!——Doesn\'t matter, I wasn\'t doing anything anyway.)',
      '去不去都无所谓。(It doesn\'t matter whether we go or not.)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'intermediate',
    formality: 'casual',
  },
  {
    slug: 'xia-ci-ba',
    characters: '下次吧',
    pinyin: 'xià cì ba',
    meaning: 'Next time / maybe next time',
    context: 'Another polite way to decline or postpone plans. Similar to 改天吧 but specifically refers to the next opportunity. Sometimes it genuinely means next time, sometimes it\'s a soft no.',
    examples: [
      '今天去不了，下次吧。(Can\'t make it today, next time.)',
      '下次吧，这次太赶了。(Next time, this time is too rushed.)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'yue-ma',
    characters: '约吗',
    pinyin: 'yuē ma',
    meaning: 'Wanna hang out? / Want to meet up?',
    context: 'A casual, often text-based invitation. Very common among friends. Can be used to suggest grabbing food, drinks, or any activity. Sometimes playfully flirtatious.',
    examples: [
      '周末约吗？(Want to hang out this weekend?)',
      '好久不见，约个饭？(Long time no see, want to grab food?)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'wo-qing-ni',
    characters: '我请你',
    pinyin: 'wǒ qǐng nǐ',
    meaning: 'My treat / I\'ll pay for you',
    context: 'Offering to pay is a big part of Chinese social culture. There\'s often a friendly "fight" over who pays the bill. Saying 我请你 before the meal sets the expectation.',
    examples: [
      '今天我请你，别客气。(Today\'s my treat, don\'t be polite.)',
      '这顿我请。(This meal is on me.)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'qu-bu-qu',
    characters: '去不去',
    pinyin: 'qù bù qù',
    meaning: 'Are you going (or not)? / Want to go?',
    context: 'A direct, casual way to ask if someone wants to join an activity. The A-not-A question pattern (去不去, 要不要, 好不好) is one of the most useful structures in Chinese.',
    examples: [
      '明天爬山，你去不去？(Hiking tomorrow, you going?)',
      '唱K去不去？(Want to go to karaoke?)',
    ],
    category: 'Making Plans & Socializing',
    difficulty: 'beginner',
    formality: 'casual',
  },

  // ===== Reactions & Opinions =====
  {
    slug: 'zhen-de-jia-de',
    characters: '真的假的',
    pinyin: 'zhēn de jiǎ de',
    meaning: 'Really?! / Are you serious? / No way!',
    context: 'An expression of surprise or disbelief. One of the most commonly used reactions in Chinese conversation. Can be a genuine question or a rhetorical exclamation.',
    examples: [
      '他辞职了！——真的假的？！(He quit his job!——Are you serious?!)',
      '真的假的，这么便宜？(No way, this cheap?)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'tai-kua-zhang-le',
    characters: '太夸张了',
    pinyin: 'tài kuā zhāng le',
    meaning: 'That\'s so exaggerated / That\'s over the top',
    context: 'Used to react to something unbelievable, excessive, or dramatic. Can be negative (prices, behavior) or positive with awe (amazing performance).',
    examples: [
      '排队两小时？太夸张了吧！(Two hour queue? That\'s ridiculous!)',
      '这个特效太夸张了。(These special effects are over the top.)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'hai-hao-ba',
    characters: '还好吧',
    pinyin: 'hái hǎo ba',
    meaning: 'It\'s okay / not bad / so-so',
    context: 'A lukewarm response. Used when something is neither great nor terrible. Chinese people often use this to be modest about achievements or to give a non-committal opinion.',
    examples: [
      '这个餐厅怎么样？——还好吧，一般般。(How\'s this restaurant?——It\'s okay, nothing special.)',
      '考试难吗？——还好吧。(Was the exam hard?——It was okay.)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'kan-qing-kuang',
    characters: '看情况',
    pinyin: 'kàn qíng kuàng',
    meaning: 'Depends on the situation / we\'ll see',
    context: 'A non-committal answer that avoids a definitive yes or no. Very commonly used in Chinese communication where directness is sometimes avoided.',
    examples: [
      '你去吗？——看情况吧。(Are you going?——Depends on the situation.)',
      '能不能做到？看情况。(Can it be done? We\'ll see.)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'mei-xiang-dao',
    characters: '没想到',
    pinyin: 'méi xiǎng dào',
    meaning: 'Didn\'t expect that / I never would have thought',
    context: 'Expressing genuine surprise at an unexpected outcome. Can be positive or negative. Used when reality differs significantly from expectations.',
    examples: [
      '没想到你中文说得这么好！(I didn\'t expect your Chinese to be so good!)',
      '真没想到他会来。(I really didn\'t expect him to come.)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'you-dao-li',
    characters: '有道理',
    pinyin: 'yǒu dào lǐ',
    meaning: 'That makes sense / Good point',
    context: 'Used to agree with someone\'s reasoning or logic. A common response in discussions that shows you\'re listening and find their argument valid.',
    examples: [
      '你说的有道理。(What you said makes sense.)',
      '有道理，我没想到这一点。(Good point, I hadn\'t thought of that.)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'shuo-de-ye-shi',
    characters: '说的也是',
    pinyin: 'shuō de yě shì',
    meaning: 'You have a point / That\'s true too',
    context: 'Acknowledging someone\'s perspective, often when they\'ve changed your mind or added a viewpoint you hadn\'t considered. Slightly more concessive than 有道理.',
    examples: [
      '说的也是，那我们换个地方吧。(You have a point, let\'s change the place then.)',
      '说的也是，我再想想。(That\'s true too, let me think about it more.)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'intermediate',
    formality: 'neutral',
  },
  {
    slug: 'zen-me-ke-neng',
    characters: '怎么可能',
    pinyin: 'zěn me kě néng',
    meaning: 'How is that possible? / That\'s impossible!',
    context: 'Strong expression of disbelief. More emphatic than 真的假的. Used when something seems completely unbelievable or defies logic.',
    examples: [
      '他一天跑了一百公里？怎么可能！(He ran 100km in a day? That\'s impossible!)',
      '怎么可能这么快就卖完了？(How can it be sold out already?)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'bu-zhi-yu',
    characters: '不至于',
    pinyin: 'bù zhì yú',
    meaning: 'It\'s not that bad / surely not / no need to go that far',
    context: 'Used to calm someone down or suggest they\'re overreacting. It sets a boundary on how extreme a situation really is.',
    examples: [
      '不至于吧，没那么严重。(Come on, it\'s not that serious.)',
      '迟到五分钟而已，不至于发火吧？(Just five minutes late, no need to get angry, right?)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'intermediate',
    formality: 'casual',
  },
  {
    slug: 'cha-bu-duo',
    characters: '差不多',
    pinyin: 'chà bù duō',
    meaning: 'Close enough / more or less / almost the same',
    context: 'One of the most versatile Chinese expressions. Can mean "almost," "roughly the same," "good enough," or "that\'s about right." Reflects a flexible, non-perfectionist attitude.',
    examples: [
      '这两个差不多，买哪个都行。(These two are about the same, either one works.)',
      '快好了吗？——差不多了。(Almost done?——Just about.)',
    ],
    category: 'Reactions & Opinions',
    difficulty: 'beginner',
    formality: 'neutral',
  },

  // ===== Work & Professional =====
  {
    slug: 'xin-ku-le',
    characters: '辛苦了',
    pinyin: 'xīn kǔ le',
    meaning: 'You\'ve worked hard / thanks for your effort',
    context: 'A very important phrase in Chinese professional and social culture. Used to acknowledge someone\'s effort or hard work. Said to delivery drivers, colleagues after a long meeting, or anyone who\'s helped you.',
    examples: [
      '辛苦了，快休息吧。(You\'ve worked hard, take a rest.)',
      '今天的会议辛苦大家了。(Thanks everyone for your hard work in today\'s meeting.)',
    ],
    category: 'Work & Professional',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'qing-duo-guan-zhao',
    characters: '请多关照',
    pinyin: 'qǐng duō guān zhào',
    meaning: 'Please look after me / I\'m in your care',
    context: 'Said when meeting new colleagues, business partners, or joining a new team. Shows humility and respect. Similar to the Japanese よろしくお願いします.',
    examples: [
      '我是新来的，请多关照。(I\'m new here, please take care of me.)',
      '初次见面，请多关照。(Nice to meet you, I\'m in your care.)',
    ],
    category: 'Work & Professional',
    difficulty: 'intermediate',
    formality: 'formal',
  },
  {
    slug: 'jia-ban',
    characters: '加班',
    pinyin: 'jiā bān',
    meaning: 'Work overtime / stay late at work',
    context: 'A word you\'ll hear constantly in Chinese work culture. Unfortunately very common, especially in tech and finance. Can be used as a verb or noun.',
    examples: [
      '今晚又要加班。(Have to work overtime again tonight.)',
      '你经常加班吗？(Do you often work overtime?)',
    ],
    category: 'Work & Professional',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'kai-hui',
    characters: '开会',
    pinyin: 'kāi huì',
    meaning: 'Have a meeting / in a meeting',
    context: 'Used to explain you\'re busy, schedule meetings, or (often) complain about too many meetings. Can be used as an excuse to avoid calls or messages.',
    examples: [
      '我在开会，等会儿再说。(I\'m in a meeting, let\'s talk later.)',
      '下午三点开会。(Meeting at 3pm.)',
    ],
    category: 'Work & Professional',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'hui-bao',
    characters: '汇报',
    pinyin: 'huì bào',
    meaning: 'Report / give an update / brief the boss',
    context: 'Used in workplace settings when presenting progress or results to a manager. A key activity in Chinese corporate culture where keeping leadership informed is important.',
    examples: [
      '这个项目需要向领导汇报。(This project needs to be reported to leadership.)',
      '每周一汇报工作进展。(Report work progress every Monday.)',
    ],
    category: 'Work & Professional',
    difficulty: 'intermediate',
    formality: 'formal',
  },
  {
    slug: 'fang-bian-ma',
    characters: '方便吗',
    pinyin: 'fāng biàn ma',
    meaning: 'Is it convenient? / Is this a good time?',
    context: 'A polite way to check before asking for something or scheduling. More considerate than directly making a request. Essential in professional communication.',
    examples: [
      '现在说话方便吗？(Is it convenient to talk now?)',
      '明天见面方便吗？(Is it convenient to meet tomorrow?)',
    ],
    category: 'Work & Professional',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'kao-lv-yi-xia',
    characters: '考虑一下',
    pinyin: 'kǎo lǜ yī xià',
    meaning: 'Let me think about it / I\'ll consider it',
    context: 'A polite way to delay a decision. In business contexts, this often means a soft no. In personal contexts, it usually means genuinely thinking it over.',
    examples: [
      '这个方案我考虑一下。(Let me think about this proposal.)',
      '考虑一下再决定吧。(Think it over before deciding.)',
    ],
    category: 'Work & Professional',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'bao-chi-lian-xi',
    characters: '保持联系',
    pinyin: 'bǎo chí lián xì',
    meaning: 'Keep in touch / stay connected',
    context: 'Said at the end of meetings, business dinners, or when parting ways. Often accompanied by exchanging WeChat contacts. More sincere than its English equivalent.',
    examples: [
      '以后保持联系。(Let\'s keep in touch from now on.)',
      '加个微信，保持联系。(Let\'s add each other on WeChat and stay in touch.)',
    ],
    category: 'Work & Professional',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'jin-kuai',
    characters: '尽快',
    pinyin: 'jǐn kuài',
    meaning: 'As soon as possible / ASAP',
    context: 'Used in work emails, messages, and conversations to indicate urgency. Very common in professional communication. Can be softened with 请 (qǐng, please) before it.',
    examples: [
      '请尽快回复。(Please reply as soon as possible.)',
      '这个需要尽快完成。(This needs to be completed ASAP.)',
    ],
    category: 'Work & Professional',
    difficulty: 'beginner',
    formality: 'formal',
  },
  {
    slug: 'he-zuo-yu-kuai',
    characters: '合作愉快',
    pinyin: 'hé zuò yú kuài',
    meaning: 'Pleasure doing business / great working together',
    context: 'Said at the conclusion of a business deal, project, or collaboration. A common sign-off in business settings that expresses mutual satisfaction.',
    examples: [
      '合作愉快！期待下次。(Great working together! Looking forward to next time.)',
      '感谢大家的努力，合作愉快。(Thanks for everyone\'s effort, it\'s been a pleasure working together.)',
    ],
    category: 'Work & Professional',
    difficulty: 'intermediate',
    formality: 'formal',
  },

  // ===== Emergencies & Help =====
  {
    slug: 'bang-bang-wo',
    characters: '帮帮我',
    pinyin: 'bāng bāng wǒ',
    meaning: 'Help me please',
    context: 'A direct plea for help. The repetition of 帮 makes it more urgent and emotional than just 帮我. Use when you really need someone\'s assistance.',
    examples: [
      '帮帮我，我找不到我的酒店。(Help me, I can\'t find my hotel.)',
      '谁能帮帮我？(Can someone help me?)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'bu-shu-fu',
    characters: '不舒服',
    pinyin: 'bù shū fu',
    meaning: 'I don\'t feel well / I\'m uncomfortable',
    context: 'Used when feeling sick or physically uncomfortable. In a medical setting, the doctor will ask 哪里不舒服 (nǎ lǐ bù shū fu, where does it hurt/what\'s wrong?).',
    examples: [
      '我不舒服，想休息。(I don\'t feel well, I want to rest.)',
      '你哪里不舒服？(Where do you feel uncomfortable?)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'guo-min',
    characters: '过敏',
    pinyin: 'guò mǐn',
    meaning: 'Allergic / allergy',
    context: 'Critical for food allergies or medication. Learn to say what you\'re allergic to: 花生过敏 (huā shēng guò mǐn, peanut allergy), 海鲜过敏 (hǎi xiān guò mǐn, seafood allergy).',
    examples: [
      '我对花生过敏。(I\'m allergic to peanuts.)',
      '这个里面有没有海鲜？我过敏。(Does this contain seafood? I\'m allergic.)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'intermediate',
    formality: 'neutral',
  },
  {
    slug: 'bao-jing',
    characters: '报警',
    pinyin: 'bào jǐng',
    meaning: 'Call the police',
    context: 'Emergency number in China is 110 for police, 120 for ambulance, 119 for fire. 报警 specifically means to report to the police.',
    examples: [
      '快报警！(Call the police quickly!)',
      '要不要报警？(Should we call the police?)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'jiao-jiu-hu-che',
    characters: '叫救护车',
    pinyin: 'jiào jiù hù chē',
    meaning: 'Call an ambulance',
    context: 'For medical emergencies, call 120 for an ambulance in China. Make sure to know the address in Chinese or have it on your phone to show to someone.',
    examples: [
      '快叫救护车！(Call an ambulance quickly!)',
      '请帮忙叫救护车，有人晕倒了。(Please help call an ambulance, someone fainted.)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'wo-de-dong-xi-diu-le',
    characters: '我的东西丢了',
    pinyin: 'wǒ de dōng xī diū le',
    meaning: 'I lost my belongings / my stuff is missing',
    context: 'Used when you\'ve lost something or suspect theft. Specify what: 手机 (shǒu jī, phone), 钱包 (qián bāo, wallet), 护照 (hù zhào, passport).',
    examples: [
      '我的手机丢了！(I lost my phone!)',
      '我的钱包丢了，怎么办？(I lost my wallet, what should I do?)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'neng-shuo-man-yi-dian-ma',
    characters: '能说慢一点吗',
    pinyin: 'néng shuō màn yī diǎn ma',
    meaning: 'Can you speak more slowly?',
    context: 'The most important survival phrase for any Chinese learner. People will appreciate your effort to understand and will usually slow down significantly.',
    examples: [
      '对不起，能说慢一点吗？(Sorry, can you speak a bit more slowly?)',
      '请说慢一点，我在学中文。(Please speak slowly, I\'m learning Chinese.)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'wo-ting-bu-dong',
    characters: '我听不懂',
    pinyin: 'wǒ tīng bù dǒng',
    meaning: 'I don\'t understand (what I\'m hearing)',
    context: 'Specifically means you can\'t understand spoken words (as opposed to 看不懂 for written text). Very useful for language learners. Often prompts people to switch to simpler words or use gestures.',
    examples: [
      '对不起，我听不懂，你能写下来吗？(Sorry, I don\'t understand, can you write it down?)',
      '他说的方言我听不懂。(I can\'t understand the dialect he\'s speaking.)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'you-ren-hui-shuo-ying-wen-ma',
    characters: '有人会说英文吗',
    pinyin: 'yǒu rén huì shuō yīng wén ma',
    meaning: 'Does anyone speak English?',
    context: 'Last resort when communication breaks down completely. In major cities and tourist areas, someone usually speaks some English. In smaller cities, younger people are more likely to know some.',
    examples: [
      '请问，有人会说英文吗？(Excuse me, does anyone speak English?)',
      '这里有会说英文的人吗？(Is there anyone here who speaks English?)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'yao-dian-zai-na',
    characters: '药店在哪',
    pinyin: 'yào diàn zài nǎ',
    meaning: 'Where is the pharmacy?',
    context: 'Pharmacies (药店/药房) are common in China and many medicines are available without prescription. You can describe symptoms and pharmacists will often recommend medicine.',
    examples: [
      '请问药店在哪？(Excuse me, where is the pharmacy?)',
      '附近有药店吗？(Is there a pharmacy nearby?)',
    ],
    category: 'Emergencies & Help',
    difficulty: 'beginner',
    formality: 'neutral',
  },

  // ===== Daily Life & Feelings =====
  {
    slug: 'lei-si-le',
    characters: '累死了',
    pinyin: 'lèi sǐ le',
    meaning: 'I\'m exhausted / dead tired',
    context: 'The 死了 (sǐ le, "to death") pattern is used as a dramatic intensifier. 累死了 is very commonly used after a long day of work, sightseeing, or exercise.',
    examples: [
      '今天走了两万步，累死了。(Walked 20,000 steps today, I\'m dead tired.)',
      '加班到十二点，累死了。(Worked overtime until midnight, I\'m exhausted.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'fan-si-le',
    characters: '烦死了',
    pinyin: 'fán sǐ le',
    meaning: 'So annoying / I\'m so frustrated',
    context: 'Used to express irritation or frustration. Another 死了 intensifier pattern. Common when dealing with annoying situations, people, or bureaucracy.',
    examples: [
      '这个问题烦死了！(This problem is so annoying!)',
      '排队排了一小时，烦死了。(Queued for an hour, so frustrating.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'jia-you',
    characters: '加油',
    pinyin: 'jiā yóu',
    meaning: 'You can do it! / Keep going! / Go for it!',
    context: 'Literally means "add oil/fuel." One of the most positive and encouraging phrases in Chinese. Used at sports events, before exams, during tough times, or to motivate anyone.',
    examples: [
      '明天考试，加油！(Exam tomorrow, you got this!)',
      '加油，我相信你！(Keep going, I believe in you!)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'man-man-lai',
    characters: '慢慢来',
    pinyin: 'màn man lái',
    meaning: 'Take your time / no rush / slowly does it',
    context: 'A comforting phrase that reduces pressure. Used to tell someone there\'s no hurry. Reflects a patient, understanding attitude. Also used when learning something new.',
    examples: [
      '别着急，慢慢来。(Don\'t worry, take your time.)',
      '学中文慢慢来，不要急。(Learning Chinese takes time, don\'t rush.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'mei-ban-fa',
    characters: '没办法',
    pinyin: 'méi bàn fǎ',
    meaning: 'There\'s nothing we can do / no way around it / can\'t help it',
    context: 'Expressing helplessness or acceptance of an unavoidable situation. Very commonly used to acknowledge that some things are beyond your control.',
    examples: [
      '堵车了，没办法，只能等。(Traffic jam, nothing we can do, just have to wait.)',
      '没办法，规定就是这样。(Can\'t help it, those are the rules.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'xi-guan-le',
    characters: '习惯了',
    pinyin: 'xí guàn le',
    meaning: 'I\'m used to it / I\'ve gotten used to it',
    context: 'Used when something that was once difficult or strange has become normal. Can be positive (adapting to a new life) or resigned (accepting something unpleasant).',
    examples: [
      '这里天气很热，但我习惯了。(It\'s very hot here, but I\'m used to it.)',
      '加班加习惯了。(I\'ve gotten used to working overtime.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'zen-me-ban',
    characters: '怎么办',
    pinyin: 'zěn me bàn',
    meaning: 'What should I/we do? / Now what?',
    context: 'Seeking advice or expressing panic when facing a problem. Can be a genuine question or a rhetorical expression of helplessness.',
    examples: [
      '手机没电了，怎么办？(Phone is dead, what do I do?)',
      '飞机取消了，怎么办？(Flight cancelled, now what?)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'gao-ding-le',
    characters: '搞定了',
    pinyin: 'gǎo dìng le',
    meaning: 'Done! / All taken care of / handled it',
    context: 'A satisfying phrase to use when you\'ve completed a task or solved a problem. Shows confidence and competence. Very casual and upbeat.',
    examples: [
      '机票搞定了！(Flight tickets are booked!)',
      '别担心，我搞定了。(Don\'t worry, I\'ve got it handled.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'casual',
  },
  {
    slug: 'lai-bu-ji-le',
    characters: '来不及了',
    pinyin: 'lái bù jí le',
    meaning: 'There\'s no time / too late / can\'t make it in time',
    context: 'Used when you\'re running out of time or have missed a deadline/opportunity. Creates a sense of urgency. The opposite is 来得及 (lái de jí, there\'s still time).',
    examples: [
      '来不及了，快走！(No time, let\'s go!)',
      '现在去还来得及吗？——来不及了。(Is there still time to go now?——It\'s too late.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'neutral',
  },
  {
    slug: 'wu-liao',
    characters: '无聊',
    pinyin: 'wú liáo',
    meaning: 'Bored / boring',
    context: 'Can describe your own state (I\'m bored) or something that\'s boring. Very commonly used among young people, especially on social media or when texting.',
    examples: [
      '好无聊啊，有什么好玩的吗？(So bored, is there anything fun to do?)',
      '这个电影太无聊了。(This movie is so boring.)',
    ],
    category: 'Daily Life & Feelings',
    difficulty: 'beginner',
    formality: 'casual',
  },
];

// Helper functions
export function getAllPhrases(): PhraseTerm[] {
  return phraseTerms;
}

export function getPhraseBySlug(slug: string): PhraseTerm | undefined {
  return phraseTerms.find(t => t.slug === slug);
}

export function getPhrasesByCategory(category: string): PhraseTerm[] {
  return phraseTerms.filter(t => t.category === category);
}

export function getRelatedPhrases(slug: string, limit: number = 4): PhraseTerm[] {
  const term = getPhraseBySlug(slug);
  if (!term) return [];

  const sameCategory = phraseTerms.filter(t => t.slug !== slug && t.category === term.category);
  const others = phraseTerms.filter(t => t.slug !== slug && t.category !== term.category);

  return [...sameCategory, ...others].slice(0, limit);
}

export function loadTranslatedPhrases(lang: string): TranslatedPhraseTerm[] {
  try {
    const filePath = path.join(process.cwd(), 'public', 'translations', lang, 'phrases.json');
    const data = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(data) as TranslatedPhraseTerm[];
  } catch {
    return phraseTerms.map(term => ({
      ...term,
      originalSlug: term.slug,
    }));
  }
}

export function getTranslatedPhraseBySlug(slug: string, lang: string): TranslatedPhraseTerm | undefined {
  const terms = loadTranslatedPhrases(lang);
  return terms.find(t => t.slug === slug || t.originalSlug === slug);
}
